### ISSUE TITLE
As PhO, I want to import and view basic Local Group data from BK

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#1]
PR: 
- https://github.com/buzzn/admin-app/pull/237
- https://github.com/buzzn/admin-app/pull/246
- https://github.com/buzzn/buzzn/pull/1287 (rake tasks for BK import)
- https://github.com/buzzn/buzzn/pull/1286 (backend)
- https://github.com/buzzn/buzzn/pull/1289 (backend)
- https://github.com/buzzn/core/pull/1292 (backend)

---
**Story:**
As PhO, I want to import all still valid and operational `local pools (groups)` from BeeKeeper into Admin App, so I can view and verify the directly associated data values.

---
**Definition of done**
**Visibility** of basic local group data, which are: 
- [x] All currently active local groups are imported (and visible on the "my groups" page). Invalid groups are identified by start_date of '00-00-0000'.
- [x] Groups have **name**, **address**, **start date** (group details page). Complete set of fields to be imported are tagged in the XLS with story number.
- [x] Groups have valid **DSO**, **TSO** and **supplier**

**excluded from this first sprint:** 
- editing data
- Groupowners Data
- Organisation (if it is an organisation)
- Members: (Bezugszählpunkte: [NUMBER], Stromnehmer EEG: [NUMBER], Stromnehmer red. EEG: [NUMBER], Drittbelieferte: [NUMBER]
- generate the display view with link to the rendered view
- statistics on top of the picture (production, consumption, Autarkie, Suffizienz) 
- link the source icons to their belonging system-site
- excluded in this design version: "invite a Traudl" 
- visibility settings are not part of this story.
---

**Technical details**
- [x] Provide fields in mockup for DSO, TSO, supplier
- [x] set up group associations to DSO, TSO and supplier and expose them in API endpoints (CM)
- [x] add import prototype to core application (in lib) (PO)
- [x] set correct DB connection for all Beekeeper ActiveRecord models (PO)
- [x] make rake task to run the actual conversion (from BK DB to Core DB) (PO)
- [x] Exclude all groups with minipool_start (date) '0000-00-00' (PO)
- [x] import name and start date (PO)
- [x] import DSO, TSO, supplier, and associate them to the group correctly (PO)
- [x] import address (use the one from the separate table which is linked by the address_id foreign key) (PO)
- [x] make rake task to convert BK MySQL dump to BK postgres (CM)
- [x] display these fields on the group detail page: name, address, start date, DSO, TSO, supplier, (default) image, sources. See https://goo.gl/XBiif6 for a list of all possible organizations.
- [x] ~~find a way to make BK MySQL dump available on staging (PO)~~
- [x] Set a strong password for all seeded users on staging (same for all users). Share the data in lastpass)
- [x] add unique index for organization slug (CM)
- [x] DISCUSS: (when to) ensure imported data meets our invariants?
- [x] make BK data available on staging, incl. new, secure user password
- [x] clarify when we'll assign the missing organizations
- [ ] clarify if we need to do sth about the PG errors on import

**Data mapping file:** https://buzzn-team.atlassian.net/wiki/x/OIAZBg
- Source tables: 
-- minipooldb.minipool.objekte
-- minipooldb.addresse

**Design and screen Mockup:**
https://invis.io/8DDUMF34P#/262879736_WF_Group_Overview_V2
PW: Wolfgang

**Comment by dottorer** [comment]
Questions from @evaklopp:

@dottorer:
Where can I find the visibility-settings?
Is there a tel number aswell as a second contact possibility?
I would like to display the numbers of powertakers aswell and the sources (pv or other), furthermore a status of the group or sth like "all systems are running" - are there any obstacles?
Is it possible to add more than one picture to a group?

**Comment by dottorer** [comment]
@evaklopp:
1. The visibility settings are currently not tracked in the admin app or the beekeeper. they are only on the paper document for the local group processing contract and accessible to Pho. I suggest we set it to the values as selected by our customers on the contracts.
2. We only allow one contact person in our data model. That seems sufficient. Each (contact) person has a phone number.
3. We can display stats like number of PTs or power sources and such without problem. Just design it and we can build it.
4. We can add whatever we like in the design. Right now, the implementation of the picture is dormant and we use a default backdrop for the group tile. Whatever is looking good we can add here.

**Comment by phillipoertel** [comment]
Thanks for the story, guys. Some feedback!

- since this is the first groups story, it should be placed before the others in the prioritized backlog (right now it's after it)
- regarding the requirement "all still valid and operational localpools": how do we know which ones to import? We could use a list of names or ids of groups to exclude, for example.
- a brief mockup of the group detail page would be helpful, including which data to show.
- the technical details of this story link to the XLS file for minipool_objekte. Is importing all fields described there part of this story, or are really only the ones mentioned here required (name, start date, address, visibility settings)? we could either discuss which fields we import in the planning (the ones that are easy, i.e. directly on the group), or you could prepare that already. 

Please update the Acceptance Criteria accordingly, so we always have up-to-date information in the first comment of the user story. That'll make working with them much easier.

**Comment by evaklopp** [comment]
Hey Phillip, 

thanks for your feedback, unluckily I had to interrupt my process of describing this first story and couldn´t finish it, now I´m back. 

According to the Design: I had a quick Review with PhO this noon and I had some changes for Pali, who will do these this afternoon. So I decided to wait with adding the screen until Pali is ready. Furthermore I would like to add some definitions to it, but this I will do on the las version of the design. 

According to your 4th point, I thought about the same question and I added more without updating the story (dammn, again this happens to me) so I have to do it again. What I would prepare for monday is a list of DoDs and things I would exclude for this first story so we can discuss. 

I found out, that it does not make any sense to me to describe the functions on a confluence site, somehow it should be directly on the Design. What do you think about that?   

Thanks for your cool insights, 

Eva

**Comment by phillipoertel** [comment]
* "What I would prepare for monday is a list of DoDs and things I would exclude for this first story so we can discuss." --> that's great
* "I found out, that it does not make any sense to me to describe the functions on a confluence site, somehow it should be directly on the Design."  --> I'm not sure what you mean by "functions", but a separate confluence document should not be required. If you prepare a wireframe and notes for yourself so you can show/describe what should happen, we'll find a way to document what needs to be written down, no need for extensive, up-front documentation.

**Comment by phillipoertel** [comment]
One more thing: editing the imported data isn't part of the story, is it?

**Comment by dottorer** [comment]
@phillipoertel Some thoughts on the points:
1. "All valid groups" : This is done by looking at the group.start_date. Pho will clean this up in BeeKeeper and the obsolete ones get a '00-00-0000'. The live ones have a real date and the future ones have a valid future date like '01-01-2099'.
2. For the fields to be included, I will tag the ones we need for this story in the XLS documents with the story number. So we know piece by piece which story will bring in which fields. Ok?

**Comment by dottorer** [comment]
3. Edit is not part of this story.

**Comment by dottorer** [comment]
@phillipoertel Talked to Pho and he already updated the start_date to '00-00-0000' per our convention as a filter for obsolete groups. If we request a new dump of the minipooldb / buzzndb pair, we can executre @mkristian 's converted script and do a fresh import.

**Comment by phillipoertel** [comment]
FYI importing and mapping the data went well. I think we are missing these organizations in our seed, @dottorer could you find out the data for them so I can add and associate them? The following are the names as given in beekeeper:

"Netz Leipzig" (netzbetreiber)
"Hamburg Netz" (netzbetreiber)
"SW Netz GmbH" (netzbetreiber)
"BEG Freising" (reststromlieferant)

There's more data missing (not much), but I worked with the old beekeeper dump today, will check with the latest one tomorrow.

**Comment by dottorer** [comment]
@phillipoertel After analysis, here is the following status:
1. I have added "Netz Leipzig GmbH" as a DSO to 
[org_seeds_v2.xlsx](https://github.com/buzzn/scrum/files/1481401/org_seeds_v2.xlsx)
2. "Hamburg Netz" is the already existing "Stromnetz Hamburg GmbH"
3. "SW Netz GmbH" is the already existing "Stadtwerke Wiesbaden Netz GmbH"
4. The "BEG Freising" is listed in Beekeeper currently with BDEW code "9911607000007" but this code no longer exists on the BDEW site. Maybe they no longer are active. I need to check with Pho.

Let me know if you need any other things. We can also ask Pho to correct the DSOs in the Beekeeper data going forward.

**Comment by dottorer** [comment]
Clarified with Pho: For BEG Freising we need to use "Freisinger Stadtwerke Versorgungs-GmbH".

**Comment by dottorer** [comment]
Added 'Freisinger' to the 
[org_seeds_v2.xlsx](https://github.com/buzzn/scrum/files/1482150/org_seeds_v2.xlsx)

**Comment by phillipoertel** [comment]
@dottorer that helped, thanks. 
I modified the data in two places before importing, could you please adapt the source/master? I wouldn't know which file to change.
1. changed the iso state code for Netz Leipzig, Saxony is SN
2. changed the slug for Freisinger Stadtwerke from "freisinger-sw" to "sw-freising" (all the other Stadtwerke follow that pattern, like "sw-landshut", etc.)

FYI: the CSV files are searchable and editable directly in the github interface (compare https://goo.gl/qz6otd). So if you're comfortable working with those, we could use that as the primary source.

**Comment by dottorer** [comment]
Updated source sheet: 
[org_seeds_v2.xlsx](https://github.com/buzzn/scrum/files/1482390/org_seeds_v2.xlsx)

**Comment by phillipoertel** [comment]
An update after importing the latest seed: Only Netzbetreiber Vattenfall is now missing. Here's the log of what' still empty but required in our DB (transmission_system_operator is "netzbetreiber",  electricity_supplier "reststromlieferant")

```
 Am Urtlgraben 15: unable to map transmission_system_operator. Beekeeper value is ''.
 Bahnhofstr. 21: unable to map electricity_supplier. Beekeeper value is ''.
 Fritz-Winter-Straße 3+7 - WA10: unable to map electricity_supplier. Beekeeper value is ''.
 Gertrud-Grunow-Straße 45 - WA12: unable to map electricity_supplier. Beekeeper value is ''.
 Heigelstraße 27B: unable to map electricity_supplier. Beekeeper value is ''.
 Hühnefeldstraße 6-8: unable to map electricity_supplier. Beekeeper value is ''.
 L.O.F.T.: unable to map electricity_supplier. Beekeeper value is ''.
 Marktplatz.1-7: unable to map electricity_supplier. Beekeeper value is ''.
 Martinusstraße 13: unable to map electricity_supplier. Beekeeper value is ''.
 Martinusstraße 13: unable to map transmission_system_operator. Beekeeper value is ''.
 Memminger Str. 16: unable to map electricity_supplier. Beekeeper value is ''.
 Minipool Schweigerweg 20: unable to map electricity_supplier. Beekeeper value is ''.
 Pariser Straße 11: unable to map electricity_supplier. Beekeeper value is ''.
 Reinmarplatz: unable to map electricity_supplier. Beekeeper value is ''.
 Ruhensdorf 6: unable to map transmission_system_operator. Beekeeper value is ''.
 Scheffelstraße 48: unable to map electricity_supplier. Beekeeper value is ''.
 Scheffelstraße 48: unable to map transmission_system_operator. Beekeeper value is ''.
 Tassiloweg 3: unable to map transmission_system_operator. Beekeeper value is ''.
 WoGe: unable to map electricity_supplier. Beekeeper value is ''.
 wagnis 4: unable to map electricity_supplier. Beekeeper value is ''.
 wagnisART - Afrika: unable to map electricity_supplier. Beekeeper value is ''.
```

We'll probably require more seed organizations once they are completed. So I'd wait for another file or info from Philipp, before looking up and adding more orgs.

**Comment by dottorer** [comment]
Thank you. I am working with Pho on completing the missing fields. As a starter I created a view to show where we have blind spots:

```
SELECT 
upper(obj.minipool_name) as Energiegruppe,
addr.strasse,
addr.hausnummer,
addr.plz,
addr.stadt,
obj.minipool_start,
obj.vertragsnummer as Abwicklungsvertrag,
obj.messvertragsnummer as Messvertrag,
obj.sg_vertragsnummer as SG_Vertrag,
obj.sn_vertragsnummer as SN_Vertrag,
obj.vertragskontonummer as Kundennummer,
own.gesellschafts_name as Betreiber,
obj.uenb,
obj.netzbetreiber,
obj.reststromlieferant


FROM minipooldb.minipool_objekte obj, minipooldb.adresse addr, buzzndb.account_new own

WHERE obj.adress_id = addr.adress_id
AND obj.minipool_start <> '0000-00-00'
AND obj.vertragskontonummer = own.fibunr
ORDER BY obj.minipool_start ASC; 
```

I will work this down with him and complete seeds accordingly. 

When will we load the existing data into STG?

**Comment by phillipoertel** [comment]
> When will we load the existing data into STG?
I just started working on it.

**Comment by mkristian** [comment]
@phillipoertel as all imported data fulfils the invariant check I added it via the AR validation. needed to make the load of the beekeeper code lazy otherwise we end up this AR validation system wide - which breaks lots of tests.

we still need to discuss (sooner or later) when to check for completeness.

**Comment by mkristian** [comment]
@phillipoertel the default-pwd is now taken from the ENV and needs to be set in ENV before running the db:seed:example_data task

**Comment by phillipoertel** [comment]
Ok. Otherwise this ticket is done, and can be tested on Heroku as soon as it's up, I guess?

**Comment by phillipoertel** [comment]
@mkristian Importing the local DB to Heroku works now, but outputs these errors about the extensions:

```
pg_restore: creating SCHEMA "public"
pg_restore: creating COMMENT "SCHEMA public"
pg_restore: creating EXTENSION "plpgsql"
pg_restore: creating COMMENT "EXTENSION plpgsql"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 3105; 0 0 COMMENT EXTENSION plpgsql
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension plpgsql
    Command was: COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';

pg_restore: creating EXTENSION "citext"
pg_restore: creating COMMENT "EXTENSION citext"
pg_restore: [archiver (db)] Error from TOC entry 3106; 0 0 COMMENT EXTENSION citext
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension citext
    Command was: COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';

pg_restore: creating EXTENSION "uuid-ossp"
pg_restore: creating COMMENT "EXTENSION "uuid-ossp""
pg_restore: [archiver (db)] Error from TOC entry 3107; 0 0 COMMENT EXTENSION "uuid-ossp"
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension uuid-ossp
    Command was: COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';
```

Do we need to do something about that?

**Comment by phillipoertel** [comment]
@dottorer there are 13 localpools with start date 2099-01-01, most of the orgs are missing there. So I assume these are in preparation, inquiries, etc. So we may need a status field on the group as well ...

**Comment by phillipoertel** [comment]
@dottorer when do you think we can import the missing data? It would be nice to do this in the scope of this ticket, then it's done and out of our minds. If not, we should make a separate ticket with just the import of those, and close this one as done.

**Comment by dottorer** [comment]
@phillipoertel  A group status would be ideal, it has in fact been envisioned to get this in. It is likely beyond the scope of this tickert, but the 13 'in preparation' groups are a sign of business picking up!

Can we import them as is or should we add a group_status field with:
- new (we have a request for a group, a prognosis is being calculated, no contracts have been signed)
- project in progress (contracts signed, project work with VNB etc underway)
- active (the group start date has passed and we are live)
- retired (project no longer actively delivering power, etc.)

Is that what you had in mind? We could quickly discuss this state machine with Pho and for the import only have 'new' and 'active' groups for now.

**Comment by dottorer** [comment]
@phillipoertel Please let me know exactly what 'missing data' you are referring to? I would like to get as much imported as sensible. Let's chat tomorrow.

**Comment by phillipoertel** [comment]
@dottorer several TSOs, DSOs and Electricity Providers are missing. As discussed, we'll import these later, when we have a newer dump.

**Comment by phillipoertel** [comment]
Regarding the Postgres extension errors: we can ignore the warnings since the Postgres Heroku already has all extensions we need. We'd like to remove UUID to get cleaner ids, though.

**Comment by phillipoertel** [comment]
Hi @evaklopp, the story can now be tested on staging. 

The last acceptance criteria isn't met, though. Several organizations don't have a transmission system operator (TSO) and/or electricity suppliers (ES) in Beekeeper (see this list https://github.com/buzzn/scrum/issues/1#issuecomment-345261722 for details). We still decided to close this ticket and add the data as part of a separate user story ("As buzzn operator I want to see the current TSOs and ES in the admin") once we get complete data from PhO.

**Comment by phillipoertel** [comment]
@evaklopp @dottorer regarding the idea of giving a group a status (like "new", "in progress", etc): we could discuss this with PhO as part of the review meeting. I'd be curious how important/useful he'd find that. If it's not super useful we can do it later (probably until we build the completeness validations).

**Comment by dottorer** [comment]
Hi @evaklopp This is also ready for review. Please test and set to done, if accepted.

**Comment by dottorer** [comment]
@scsirdx : Couple of things I noted on this story:

1. Start Date is '2016-12-01' and should be '01.12.2016'
2. The font is still weirdly pixelated in Chrome for me, maybe we can improve on that. I will open a technical ticket for this specific issue.

**Comment by dottorer** [comment]
See https://github.com/buzzn/admin-app/issues/243 for pixelation issues.

**Comment by scsirdx** [comment]
@dottorer 
I'll fix date in #4

**Comment by evaklopp** [comment]
Hey @scsirdx I found this on all group view sites: 
![bildschirmfoto 2017-11-23 um 10 01 19](https://user-images.githubusercontent.com/22292464/33165104-de47d380-d035-11e7-874c-b8132629f981.png)

**Comment by evaklopp** [comment]
Hey Pavel @scsirdx is there a reason why you didn´t sticked to the order of the labels/data which we set in the design? It is important for userflow to have the exact order, like in the design in InVision or as here: 
![bildschirmfoto 2017-11-23 um 10 11 24](https://user-images.githubusercontent.com/22292464/33165415-069d309a-d037-11e7-95e8-a6168f185339.png)

**Comment by evaklopp** [comment]
@scsirdx please show/write the start date date always like this: DD.MM.JJJJ germans love this order and they used to read "." instead of "-" between the numbers. 
![bildschirmfoto 2017-11-23 um 10 16 19](https://user-images.githubusercontent.com/22292464/33165494-61a5383e-d037-11e7-8fe2-73e71b6e0771.png)

thank you

**Comment by evaklopp** [comment]
@phillipoertel at the moment I can´t check the first DoD of this ticket, because I don´t know how to be sure that all current LCPs are in this list. Is there a  list? Do I have to check each of them?

**Comment by dottorer** [comment]
@evaklopp This would be easiest to check for Pho himself. I can give you a list but it uses the same logic as the import, so only Pho can validate the completeness. He can also give you a count of valid groups.

**Comment by scsirdx** [comment]
@evaklopp 
1. Yes, we have problem with our current build system, so translations are not always loaded. I cleaned cache, so now you'll see labels.
2. Can you specify the order of this fields?
3. Date format is changed in #4

**Comment by scsirdx** [comment]
@evaklopp translations are there.

**Comment by evaklopp** [comment]
@scsirdx according to 2. of your comment: the order of the fields should be exactly the order which is in the design I posted before, which is: 
Groupname/Gruppenname
Address/Adresse
Start date/Starttermin
Visibility/Sichtbarkeit 

from top to down.

**Comment by scsirdx** [comment]
@evaklopp Should i remove energySources/tso/dso/es ?

**Comment by evaklopp** [comment]
@scsirdx please remove source only, see my edited post above. thanx

**Comment by scsirdx** [comment]
@evaklopp Done.

**Comment by evaklopp** [comment]
Whoooohoo and Hurray, I tested and close this now!
