### ISSUE TITLE
make sorted lists stay sorted

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#109]
**PR**
- https://github.com/buzzn/admin-app/pull/267
---

**User story**

As a Pho 
I want a list which I sorted to stay sorted even if I click to another link and go back to the site, where I sorted the list. 

---

**Definition of done**

- [x] lists stay sorted independently

e.g. system setup -page: if I sort the Meter numbers, click to a meter detail page, come back to the setup-page: the meter list isn´t sorted anymore. should stay like I sorted it before. 

---

**Technical details**

_Frontend_

- [x] Store sort order for each table in LocalStorage using `rootType.${id}.subType` path in `ui` settings.

**Comment by scsirdx** [comment]
@evaklopp 
Questions:
1. Sort settings should be saved per object id or per object type?
2. Sort settings should be saved for each table or only for top-level tables (big ones)?

**Comment by evaklopp** [comment]
just for documentation, slack discussion: 
oh, hey, I have no idea what makes the difference in the first question…. 2nd: ideally yes, for each table. Is that possible?

chipjuggler [21:57]
Regarding the 1st question:
1st option is to make sort order saved by object type, so for example if user opens powertakers list and changes sort order to name(desc), then _all_ powertaker lists tables for all groups will be sorted this way.
2nd option is to make sort order saved by object id. And in this case sort order will be different for every object list out there and it will be possible to have for example powertaker list sorted somehow for some specific group. But at the same time it will require to sort every table of the same type if user is not satisfied with the current order.
It’s a UX question.

eva [21:59]
ok, now I understand let me think
I´ll go for the 2nd option, save by object ID. Reasons: a user does´nt expect a table to be sorted when he is not actually working with it, it would be hard to find out that sorting this table type influences all the other tables of this type. a user might want to sort the tables of different groups differently.

**Comment by evaklopp** [comment]
great work @scsirdx! Thank you, closing!
