### ISSUE TITLE
Import powertaker contract data (power giver supplied)

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#115]
**PR**
- https://github.com/buzzn/core/pull/1362
- https://github.com/buzzn/core/pull/1366

**User story**

As PhO 
I want to see in the new system all the powertaker contracts that are supplied by the power giver 
so that I can access them everytime. 

---

**Definition of done**

- [x] import all powertaker contract data for registers that are supplied by the power giver:  
 

- old_supplier_name, old_ customer_number, old_account_number, 

- third_party_renter_number, third_party_billing_number, renewable_energy_law_taxation 
- [x] link to contract from pt detail

exclude: 
- tariffs #123
- payments #124
- gap free history per register for 2017 (included ended contracts) #120 
- link the powergiver person

---
**XD**

- [x] Design contract page
https://projects.invisionapp.com/d/main#/console/12205665/273221757/comments/91784980

**Technical details**

_Frontend_

-- to be revisited once spec is finalized -- 

----------

Draft: 

- [x] Implement header (contractor, customer, contract status (badge), link to register). Compare/reuse code from meter header if it makes sense
- [x] From PT details, link contract number to contraxct details page 

_Backend_

- [x] enhance import of contract for old_supplier_name, old_ customer_number, old_account_number, third_party_renter_number, third_party_billing_number, renewable_energy_law_taxation 
- [x] update API endpoint

**Comment by dottorer** [comment]
Basic query (on dev schema) on how to map data:

```
Select
contract_number as BK_Vertragsnummer,
contract_number_addition as BK_Nummernzusatz,
customer_id as powertaker_id, 
contractor_id as powergiver_id,
begin_date as BK_Bezugsbeginn,
end_date as BK_Bezugsende,
register_id,
status as BK_Status,
old_supplier_name as BK_Vorlieferant,
old_customer_number as BK_Kundennummer_alt,
old_account_number as BK_Vertragskontonummer_alt,
third_party_renter_number as BK_mieternummer,
third_party_billing_number as BK_rechnungsnummer,
renewable_energy_law_taxation as BK_eeg_umlage,
as BK_drittbelieferung,

from public.contracts 
where type = 'Contract::LocalpoolPowerTaker'
order by contract_number ASC, contract_number_addition ASC
```

**Comment by evaklopp** [comment]
@dottorer are Tariffs ans Payment part of this import-story? I would create a new story for it, seems to be a big ticket already.

**Comment by dottorer** [comment]
@evaklopp We need a separate story for tariffs. This is a completely separate items whereby we need to analyze the current structure in BK...

**Comment by dottorer** [comment]
@mkristian @scsirdx This is in progress for the sprint but we have not detailed out the technical todos on it yet. What would it take to build the import for the remaining fields (contracts already coming in with the PTs) and expose them in the API for a front end page for Pavel to build based on the UX design?

**Comment by mkristian** [comment]
@dottorer the API and import bits are done.

**Comment by scsirdx** [comment]
@dottorer We discussed it, and decided to implement most of the fields that are listed in UI prototype (not all of them available), but they will be not editable. Is it ok?

**Comment by dottorer** [comment]
@mkristian Excellent, I updated the tech details as such.

Then we need @scsirdx to outline the front end bits to implement the design and check them off as we complete them.

**Comment by dottorer** [comment]
@scsirdx Fields from prototype are not editable as part of this story, correct.

**Comment by scsirdx** [comment]
neueinzug, vollmacht erteilt, all bankaccount, tariffs and zahlungen fields are omitted.

**Comment by evaklopp** [comment]
@scsirdx 
Testing: 
e.g. https://staging-admin.buzzn.io/groups/890fbef0-1124-4cf3-a026-1dd91f58a450/powertakers/7ec0f168-e0ae-4042-9963-edbd5c81b2d6 

- Field "EEG Umlage" shows "admin.contracts.F"
- field "contractor"/"Vertragsgeber" is displayed as "ADMIN.CONTRACTS.CONTRACTOR"

**Comment by scsirdx** [comment]
@evaklopp I fixed missing german translation, but this eeg value is unknown.
@dottorer Is there any confluence page with eeg values translations?

**Comment by scsirdx** [comment]
Anyways it's not an admin-app issue, but i18n buzzn package.

**Comment by phillipoertel** [comment]
@scsirdx here's the mapping for the EEG Umlage values: https://github.com/buzzn/core/blob/master/app/models/contract/base.rb#L20-L24
German translations:
full: voll
reduced: reduziert
null: keine

**Comment by scsirdx** [comment]
Done.

**Comment by evaklopp** [comment]
Great job! I accept the story, closing!
