### ISSUE TITLE
Import Display View settings from BK

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#117]
**User story**

As Pho
I want to control in BeeKeeper which groups have Display View enabled
so that I don't have to redo this setting in Production after each data re-import.

---

**Definition of done**

- [ ] a field on minipool_objekte holds and agreed upon value to denote "Display=Yes"
- [ ] the import process translates this flag into display view = TRUE for the group
- [ ] all groups consequently show the display view in production after a new data import

---

**Technical details**

_Frontend_

- [ ] ...

_Backend_

- [ ] ...

**Comment by dottorer** [comment]
@evaklopp This should be tackeld in a nearby sprint so we keep  the display view ON for the right groups ansd Pho has control in the BK backend for now.

**Comment by dottorer** [comment]
@evaklopp I think @phillipoertel has a solution in place already where we keep a shortlist of groups. I think we can document that and close this ticket, if you both agree.

**Comment by phillipoertel** [comment]
yes, this can be closed.

**Comment by evaklopp** [comment]
Ok cool, is there anything we need to document here, @phillipoertel ?

**Comment by phillipoertel** [comment]
Yes, there is. Do the following to preserve the display app visibility settings:

1. run this

```
heroku run rails c --app=buzzn-core-production # it's 'bin/console' after next deploy

irb> Group::Localpool.where(show_display_app: true).pluck(:name).sort
```

2. replace this array: https://goo.gl/rK8nxv with the output you get
3. run the beekeeper import and push the db with the usual rake tasks.

/cc @mkristian

**Comment by evaklopp** [comment]
closing, solved.
