### ISSUE TITLE
no-rails branch

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#119]
**User story**

As a developer
I want to reduce the code dependency on Rails
so that I have a cleaner and more robust code base.

---

**Definition of done**

- [ ] All obsolete code usages of Rails have been removed.

---

**Technical details**

_Backend_

- [x] remove rails autoload and do it manually
- [x] run all the config/initializers manually
- [x] skip the rails boot altogether
- [x] remove obsolete unused code if possible, i.e. if not used by the tests
- [x] new or adjusted bin scripts (console, server, rspec, rake) to start things in the right context
- [x] mongo DB is not actively used and the railtie of the mongoid gem is not initialized - put mongo to rest and do not check it in the health check.

**Comment by dottorer** [comment]
@mkristian @phillipoertel Please fill out the tech details as bullet points for the major cateogires of things we are removing in this no-rails effort. That way we have a list for posterity and can track the removal in the next days.

**Comment by dottorer** [comment]
And if we could add a rough size so we know what we achieved...thanks!

**Comment by mkristian** [comment]
@evaklopp just visit staging: https://staging-display.buzzn.io/fritz-winter-strasse or any other group. if it works this is done.

**Comment by evaklopp** [comment]
staging is working, closing!
