### ISSUE TITLE
gap free history of contracts for all group registers

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#120]
**PR**

- https://github.com/buzzn/core/pull/1376
- https://github.com/buzzn/admin-app/pull/264

**User story**

As Pho
I want to have a valid contract for all times since 2017 for every register
so that all energy consumption is correctly billed to a PT. 

---

**Definition of done**

- [x] ~~import all contracts of the registers of a group, starting 2017~~
- [x] every register has a valid contract which is linked for every timespan, since the start of the energy group
- [x] the end date of a contract is the start-date of the new contract

- [x] fill in the gaps "automatically" with a new contract with the groupowner as powertaker
- [x] show the list of the contracts in the contracts-tab of the register

---
**XD**
see list of contracts for every register here: https://projects.invisionapp.com/d/main#/console/12205665/266638569/comments/91710863 

**Technical details**

_Frontend_

- [x] implement contracts tab on register page
- [x] get data with the API call to `register?include=contracts`

_Backend_

- [x] API: extend register endpoint to allow including the contracts
- [x] identify if there are any gaps ~~in 2017~~
- [x] create gap contracts (LocalpoolPowerTaker):
   - [x] contract number and addition: contract number taken from localpool, number addition: use current max number + 1
   - [x] review a few of the generated gap contracts for plausibility
   - [x] ensure gap contract of -609 days (60009/59) is gone after new BK import
- [x] set customer for gap contracts ~~from beekeeper dump (in dump 2018-01-05, sea_4_buzzid)~~ from list provided by PhO/Ralf
 - [x] set start and end dates following our logic, i.e. use continuous dates ~~following beekeepers logic, i.e. the contract starts one day after the previous one, and ends one day before (to be revisited after clarification with @dottorer)~~ 
  
- [ ] identify if there are any overlaps ~~in 2017~~

**Comment by dottorer** [comment]
@phillipoertel Analysis part 1:

Based on 
```
select 
sn.vertragsnummer as contract,
sn.nummernzusatz as contract_addition,
sn.buzznid as register,
sn.bezugsbeginn as begin_dt,
sn.bezugsende as end_dt

from minipooldb.minipool_sn sn

-- more than one contract for register exists
where exists (
SELECT 
sn2.vertragsnummer,
sn2.buzznid,
count(sn2.buzznid)

FROM minipooldb.minipool_sn sn2

WHERE sn2.vertragsnummer = sn.vertragsnummer
AND sn2.buzznid = sn.buzznid     
group by sn2.vertragsnummer, sn2.buzznid
having count(sn2.buzznid) > 1 )

order by 
sn.vertragsnummer asc,
sn.buzznid asc,
sn.bezugsbeginn asc
```
I created an overview showing if there are gaps per contract and how big it is:
[contractsgaps.xlsx](https://github.com/buzzn/scrum/files/1680991/contractsgaps.xlsx)

If not no gap, most of them are offset by exactly one day. And there are some outliers to clean up with Pho.

**Comment by phillipoertel** [comment]
@dottorer I found the following gaps that need to be filled:
```
Contract 60006/2: 2013-09-11 - 2013-12-31 (gap of 32 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60006/5: 2014-02-01 - 2015-10-31 (gap of 45 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60008/16: 2014-07-14 - 2015-12-31 (gap of 61 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60008/50: 2014-10-01 - 2015-12-31 (gap of 32 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60010/4: 2014-03-25 - 2015-12-31 (gap of 67 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60010/6: 2014-03-25 - 2015-12-31 (gap of 45 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60010/21: 2014-03-25 - 2017-03-29 (gap of 10 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60009/14: 2014-09-04 - 2016-09-30 (gap of 14 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60009/19: 2015-11-03 - 2016-06-30 (gap of 32 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60009/59: 2014-05-01 - 2015-12-31 (gap of -609 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60015/11: 2014-12-15 - 2016-04-28 (gap of 3 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60015/82: 2015-12-01 - 2016-05-31 (gap of 31 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60015/41: 2015-02-15 - 2016-05-11 (gap of 21 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60014/7: 2014-06-30 - 2015-06-30 (gap of 32 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60030/14: 2015-12-01 - 2016-11-28 (gap of 3 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60044/2: 2016-04-12 - 2016-10-31 (gap of 31 days filled with a 'Leerstandsvertrag' (gap contract))
```

The gap of -609 days is caused by a duplicate 3rd party contract it seems, maybe PhO can fix this up. I'll find a workaround meanwhile.

The gaps  are from these localpools; which customer should be used?
```
    Cherubinistr. 4-8
    Gertrud-Grunow-Straße 45 - WA12
    Gotthardstraße 47
    Mehrgenerationenplatz Forstenried
    wagnis 4
```

**Comment by dottorer** [comment]
@phillipoertel From Pho for gap contracts:

- Cherubinistr. 4-8 = 60009/8
- Gertrud-Grunow-Straße 45 - WA12 =60030/37
- Gotthardstraße 47 =60010/1
- Mehrgenerationenplatz Forstenried = 60015/73
- wagnis 4 = 60008/52 

Issue on 60009/59 he fixed.

**Comment by dottorer** [comment]
@phillipoertel @mkristian @evaklopp It is important to identify which contracts are in fact 'gap contracts'. I think we will need this to mark the billing bricks in blue as shown [here](https://projects.invisionapp.com/d/#/console/12205665/276543633/comments/92825765).

Can we / do we track this on the contract and also expose on the API?

**Comment by phillipoertel** [comment]
The latest beekeeper dump gives us three more localpools with gaps in their contracts (strange, but maybe it's also an import code change I did that caused that). 

Here's the full list of gap contracts now. The shown contract number is for the "real" contract that precedes the gap: 

```
Contract 60006/2: 2013-12-31 - 2014-02-01 (gap of 32 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60006/5: 2015-10-31 - 2015-12-15 (gap of 45 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60008/16: 2015-12-31 - 2016-03-01 (gap of 61 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60008/50: 2015-12-31 - 2016-02-01 (gap of 32 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60010/4: 2015-12-31 - 2016-03-07 (gap of 67 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60010/6: 2015-12-31 - 2016-02-14 (gap of 45 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60010/21: 2017-03-29 - 2017-04-08 (gap of 10 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60009/14: 2016-09-30 - 2016-10-14 (gap of 14 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60009/19: 2016-06-30 - 2016-08-01 (gap of 32 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60015/11: 2016-04-28 - 2016-05-01 (gap of 3 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60015/82: 2016-05-31 - 2016-07-01 (gap of 31 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60015/41: 2016-05-11 - 2016-06-01 (gap of 21 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60014/7: 2015-06-30 - 2015-08-01 (gap of 32 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60030/14: 2016-11-28 - 2016-12-01 (gap of 3 days filled with a 'Leerstandsvertrag' (gap contract))
Contract 60044/2: 2016-10-31 - 2016-12-01 (gap of 31 days filled with a 'Leerstandsvertrag' (gap contract))
```

I didn't know which customer to use for the three new localpools, for now I'm using the one that pays the "Allgemeinstrom" contracts:

```
'mehrgenerationenplatz-forstenried' => '60015/73', # Wogeno München eG
'hofackerstrasse'                   => '60006/3',  # Willi Kral
'scheffelstrasse'                   => '60044/7'   # VRD GbR
```

Please let me know if those are correct.

**Comment by dottorer** [comment]
@phillipoertel  Verified with Pho that three new groups have the right SN-#.

**Comment by evaklopp** [comment]
This story needs to be doublechecket with PhO, I´m accepting it! THanks for your great work, @phillipoertel !
