### ISSUE TITLE
multi-threaded auth module

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#121]
**User story**

As a developer
I want to leverage an oAuth module that can handle concurrent requests
so that I can issue concurrent requests to Discovergy API.

---

**Definition of done**

- [ ] no more concurrency issues on Discovergy call with thread count > 1

---

**Technical details**

_Backend_

- [ ] complete research for the root cause of the concurrency issues in our Dsicovergy call for charts
- [ ]

**Comment by dottorer** [comment]
@mkristian @phillipoertel @evaklopp  Here is the technical story to address the issues we saw this week on authenticating against the Discovergy API. Before we switch any modules, we need to crisply identify the root cause and then devise a solution proposal with an effort estimate. Imho this should be slated for the coming iteration.

**Comment by mkristian** [comment]
@dottorer there is nothing to do here as the problem got fixed and solved yesterday: https://github.com/buzzn/core/commit/2978780929456d7d0dfcb5582452eef0d0613539

with explanation of root cause.

**Comment by dottorer** [comment]
@mkristian So we fixed the root cause and can now handle multi-threaded oauth in the API calls just fine? All found and fixed? If so, I can just close this ticket as no longer applies - yeah!

**Comment by mkristian** [comment]
@dottorer all found and fixed by one line of code :)
