### ISSUE TITLE
Import powertaker contract data (third party supplied)

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#122]
**PR**
- https://github.com/buzzn/admin-app/pull/263
- https://github.com/buzzn/core/pull/1374
- https://github.com/buzzn/core/pull/1378
---

**User story**

As PhO 
I want to see in the new system all the powertaker contracts that are supplied **by a third party** 
so that I can see the complete set of contracts. 

---

**Definition of done**

import all powertaker contract data for registers that are supplied by a third party and show as following:
- [x] contract number and addition, 
- [x] status (active, closed/ended), 
- [x] start date, end date (if ongoing, date in 2050), 
- [x] register
- [x] show in PT-list:  instead of the PT-name, show "drittbeliefert"

---
**XD**

- [x] make version for party supplied pts

- see the screen: https://projects.invisionapp.com//share/Z8FK2JAM4/#/screens

**Technical details**

_Frontend_

- [x] verify list of contracts still works
- [x] refactor contract component

_Backend_

- [x] new model Contract::LocalpoolThirdParty
- [x] new resource
- [x] check if/what needs to be refactored between Contract::LocalpoolPowerTaker and the new contract
- [x] add third party contracts to (existing) powertaker contracts endpoint
- [x] also import all minipool_sn records where drittbelieferung is 1
- [x] don't import contractor, customer and addresses (import as little as possible).

**Comment by dottorer** [comment]
@evaklopp Breaking down the contract import in registers that are supplied by the PG (prio1) and the registers that are supplied by a third party. We need a lot less info about the 3rd party contracts, but we do need to import / track them in order to calculate the correct 'Stromkennzeichnung' (although we do not invoice them).

**Comment by phillipoertel** [comment]
@mkristian did you check all the DoD that are implemented?

**Comment by mkristian** [comment]
@phillipoertel thanks - I use to forget the DoD

**Comment by evaklopp** [comment]
@phillipoertel @mkristian I can´t find any drittbelieferte contracts in staging. Is it there? As far as I know (doublechecked it with PhO today) the Cherubinistr, UDE7, Gotthardstr should have third party contracts. But I can´t find. Any hints?

**Comment by mkristian** [comment]
@evaklopp quite likely I need to push the DB as well for them to pop up

**Comment by mkristian** [comment]
@evaklopp third-party contracts are online now. but I need to find out how to restore the images of the powertaker list (or elsewhere). for to test this ticket things are online.

**Comment by phillipoertel** [comment]
> but I need to find out how to restore the images of the powertaker list (or elsewhere).

@mkristian set the following in `.env.local`
```
ASSET_HOST=https://staging-files.buzzn.io
AWS_ACCESS_KEY=...
AWS_SECRET_KEY=...
AWS_REGION=eu-west-1
AWS_BUCKET=buzzn-core-staging
```

then run `rake beekeeper:person_images:attach`. This will add the images to your local Person records and upload the images to the staging AWS bucket. Then push the local DB to Heroku staging.
Alternatively you could just run `rake heroku:update_db:staging` which will do a full beekeeper import and push to Heroku in one command.

**Comment by mkristian** [comment]
@phillipoertel thanks - just found the tasks. but the missing bits were the AWS config and just wanted to ask you :)

**Comment by phillipoertel** [comment]
You're welcome. In case you don't have them, the AWS credentials are also in lastpass.

**Comment by evaklopp** [comment]
Hey @scsirdx or @mkristian 
1. I´m here: https://staging-admin.buzzn.io/groups/2beb465f-1c57-46d4-9821-4cecda2d1e8b/powertakers/active and why does in most cases a click on any third party supplied register name opens up the systempage, e.g. this: https://staging-admin.buzzn.io/groups/2beb465f-1c57-46d4-9821-4cecda2d1e8b/system ? In very view cases it jsut says 404 I cant remember... Why? 
2. on the detail page of the third party supplied contract the Powergiver/Stromgeber should be "drittbeliefert". Because we don´t know who is it. As far as I understood it...is that correct?

**Comment by scsirdx** [comment]
@evaklopp 
1. fixed in #152 
2. maybe. I didn't get the question.
2. fixed

**Comment by evaklopp** [comment]
2. The "Stromger"/powergiver here on the contract detail page we don´t know, so it must be third party supplied/"drittbeliefert". So if we have a third party supplied contract, it is not the PG-name which we show here in the PG-field. Because it is third party supplied, we have to display "drittbeliefert".

**Comment by scsirdx** [comment]
@evaklopp I can't see powergiver in https://projects.invisionapp.com//share/Z8FK2JAM4/#/screens detail page.
Or you're talking about different page?

**Comment by dottorer** [comment]
@mkristian This is the correct mockup page and we are not showing the power giver at all, which is correct. So if we make it look like that, all is well.

**Comment by mkristian** [comment]
@scsirdx I guess above comment from @dottorer is for you

**Comment by scsirdx** [comment]
@mkristian Then i don't understand @evaklopp question.

**Comment by mkristian** [comment]
@scsirdx let clarify in the standup

**Comment by evaklopp** [comment]
In case of a third party supplied contract, the powergiver-field still shows sth like "ELEMENTAR HAUSVERWALTUNG". Example: https://staging-admin.buzzn.io/groups/4caa2934-f517-468f-a00f-943259702202/powertakers/84731784-715a-4adc-bf59-26ed0f5484e8

In case of a third party supplied contract, this field should display: "drittbeliefert" (third party supplied).

**Comment by evaklopp** [comment]
finaly done, great work, thanks, closing!
