### ISSUE TITLE
import tariffs to PT contract data

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#123]
**PR**
- https://github.com/buzzn/admin-app/pull/265
- https://github.com/buzzn/core/pull/1382
- https://github.com/buzzn/core/pull/1379
- https://github.com/buzzn/core/pull/1381
- https://github.com/buzzn/console/pull/3
---

**User story**

As PhO
I want to see the tariff of a group
so that I know if the calculation is correct.

---

**Definition of done**

- [x] create tariff page on first nav level with a list.
- [x] The list contains 1. name of the tariff, beginn date, end date, base price €/month, energy price cents/kWh, number of contracts using this tariff
- [x] import the current/active tariff. name it with "Tarif 1" if it has no names. 
- [x] every PT-contract has to have a tariff in 2017.
- [x] preorder the list by the begin date of the tariff

excluded: 
- process of a pricing round/set up new prices, replace old tariffs with new
- exclude historic tariffs before 2017

---
**XD**

- [x] design tariffs page on the first nav level with the content of the DoD

current tariff list page: https://projects.invisionapp.com/d/main#/console/12205665/276301954/preview

historic: https://projects.invisionapp.com/d/main#/console/12205665/276146841/preview

**Technical details**

_Frontend_

- [x] rename 1st level item "Prices" to "Tariffs"
- [x] show these columns: NAME | BEGIN DATE | END DATE | BASE PRICE | KWH PRICE
- [x] API call: localpools/{localpool-id}?includes=tariffs
- [x] display baseprice in Euros, example € 3,00 (German)
- [x] display kwh in Cents, example "28,9 Cent"
- [x] preorder the list by the begin date of the tariff

_Backend_

- [x] Console: rename table "prices" to "tariffs", and fix display of tariffs
- [x] convert baseprice_cents_per_month to DB type double 
- [x] name every imported tariff, starting with "Tariff 1"
- [x] determine end date by following contract (set as done in contracts)
- [x] every active contract on the group is assigned the active tariff (other cases (ended contracts) to be implemented after clarification with @dottorer).
- [x] ensure console also shows the tariffs

**Comment by dottorer** [comment]
Basic query to get data imported:

```
SELECT
obj.minipool_name as Groupname,
obj.vertragsnummer as LGPc,
'Standard' as name,
pr.grundpreis * 100 as baseprice_cents_per_month,
pr.bezugspreis as energyprice_cents_per_kilowatt_hour, 
pr.datum as begin_date 

FROM minipooldb.minipool_preise pr, minipooldb.minipool_objekte obj

where obj.vertragsnummer = pr.vertragsnummer

ORDER BY pr.vertragsnummer ASC, begin_date ASC
```

**Comment by mkristian** [comment]
@evaklopp suppose a group has 3 tariffs, shall the oldest be named `Tariff 1`, the second oldest `Tariff 2` and the latest `Tariff 3` ?

**Comment by dottorer** [comment]
@mkristian Sounds good to me on tariff 1/2/3.

**Comment by mkristian** [comment]
@dottorer @evaklopp 
I activated the invariant check on contracts and added another invariant on the tariffs covering of the contracts. the problems I get are:
```
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: 90005/5)
Validation failed: Tariffs ["tariffs must cover beginning of contract"] (meter buzznid: 90041/68)
Validation failed: Tariffs ["tariffs must cover beginning of contract"] (meter buzznid: 90041/80)
Validation failed: Tariffs ["tariffs must cover beginning of contract"] (meter buzznid: 90041/79)
Validation failed: Tariffs ["tariffs must cover beginning of contract"] (meter buzznid: 90041/78)
Validation failed: Tariffs ["tariffs must cover beginning of contract"] (meter buzznid: 90041/77)
Validation failed: Tariffs ["tariffs must cover beginning of contract"] (meter buzznid: 90041/75)
Validation failed: Tariffs ["tariffs must cover beginning of contract"] (meter buzznid: 90041/76)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: 90043/1)
Validation failed: Tariffs ["tariffs must cover beginning of contract"], Register ["meter.group must match contract.localpool"] (meter buzznid: 90049/4)
Validation failed: Tariffs ["tariffs must cover beginning of contract"], Register ["meter.group must match contract.localpool"] (meter buzznid: 90049/5)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: 90056/94)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: 90048/29)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: 90076/11)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: 90076/12)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: 90061/53)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: 90059/19)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: P7661)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: T92401)
Validation failed: Register ["meter.group must match contract.localpool"] (meter buzznid: W32884)
```

for group `90041` and `90049` a single dummy Preise on beekeeper would make this consistent. I also could create this 'Tariff 0' on the fly for these two groups or be less strict on check (least preferred as it would be helpful to ensure that each contract has tariffs covering its period).

 The register thing just popped up as a byproduct and it is scary the contract belongs to different localpool then the register. I will investigate a bit. either it can be easily fixed or I lift the check and make a new user-story out of it (we can not leave the import like this as these inconsistency leads to hard to debug problems later on)

**Comment by mkristian** [comment]
the register.meter.group was an easy fix, it was just not set !

**Comment by dottorer** [comment]
@mkristian Should the count of contracts that a tariff is in use for be populated already or not yet? Looking real nice otherwise to see tariffs in the system now...getting closer and closer to billing fun!!!

**Comment by mkristian** [comment]
the PR https://github.com/buzzn/core/pull/1379 will add this to the API - not on master yet as it needs review. yes, billing sound like fun, really !

**Comment by phillipoertel** [comment]
@mkristian all PRs are reviewed and merged; can this be moved to test?

**Comment by mkristian** [comment]
@evaklopp here you see an example of tariffs being imported and displayed: https://github.com/buzzn/scrum/issues/142#issuecomment-364094655

**Comment by evaklopp** [comment]
great work, accepting and closing the story!
