### ISSUE TITLE
Disable AWS

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#125]
**User story**

As BUZZN 
I want to get rid of AWS
Becuase we don´t need it anymore

---

**Definition of done**

- [x] backup data
- [x] disable servers/infrastructure

---

**Technical details**

_Backend_

- [x] archive/delete unused S3 buckets
- [x] remove styleguide.buzzn.io bucket
- [x] delete CloudFront Distributions for styleguide and buzzn.s3.amazonaws.com
- [x] check the server logs if there are any requests coming in
- [x] ~~make tar archive of each Rails directory on the EC2 instances, copy it to backup bucket, then~~ turn off EC2 instances.
- [x] remove load balancers
- [x] snapshot and remove RDS databases
- [x] browse our AWS admin interface and turn off everything else that's not needed

**Comment by phillipoertel** [comment]
@dottorer the following list shows the cost composition of our AWS account (month to date). 
Only S3 and Cloudfront (contained in Sonstige Services) remain, so we should be paying less than $1 from February on.

![bildschirmfoto 2018-01-16 um 11 15 40](https://user-images.githubusercontent.com/5188/34983683-9d2a7594-faae-11e7-858c-73ce0d409f91.png)

**Comment by dottorer** [comment]
Sensational! Great to turn this off....

**Comment by dottorer** [comment]
@phillipoertel How should we verify this as done? The aws ping already fails so good to close?

We need to remove the new relic ping as well i guess.

**Comment by phillipoertel** [comment]
@dottorer regarding testing: the only obvious thing is that  aws-core.buzzn.io/api/display/groups isn't available any more. But I could give you a quick tour of the AWS interface and show you what's still alive and what it is used for; good to spread the knowledge IMHO.
I already turned off the new relic monitoring. That account (https://rpm.newrelic.com/accounts/791323) also has the monitoring for www.buzzn.net, so I can't turn it off completely.

**Comment by dottorer** [comment]
Reviewed with @phillipoertel - All clear in AWS.

We are using:
1. S3 buckets for display / admin for prod/staging/dev domains
2. corresponding CloudFront entries
3. only snapshots of prior RDS

All else has been cleanly removed.
