### ISSUE TITLE
import list of all the Organisation powertakers of a group

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#130]
**PR**
----

**Story**
As PhO I want to import and see all the Organisations powertakers according to the group they belong to in a list.

---
**DoD**

- [x] all Organisation powertakers are shown in list.
- [ ] no duplicated Organisation are created.

excluded as long we don´t have the detail pages:  

- link org name to the pt-detail page 
- link the contract number to the contract--data details page

---
**XD**

- [x] prepare list of PTs and use this screen: https://projects.invisionapp.com/d/main#/console/12205665/256909734/comments

- [x] the list is sorted from A-Z acoording to the powertaker Name

- [x] In the list I see 4 columns, 1. Name, 2. the register name, 3. status, 4. startdate of the contract in the list like here: https://staging-console.buzzn.io/admin/groups/2c7d6a7d-d51c-4e72-9811-e3a593256938

list tab 1:  current https://projects.invisionapp.com/d/main#/console/12205665/256909734/comments 

list tab2: List of former powertakers
https://projects.invisionapp.com/d/main#/console/12205665/273358584/preview

---

**Technical details**

_Frontend_

- [x] use default organization image provided by Pali

_Backend_

- [x] import contract data from beekeeper table `minipool_sn` where `drittbelieferung` is 0 and kontaktdaten.rechtsform is not "Privatperson".
- [x] identify existing, already imported organizations and reuse them.
- [x] make sure to strip imported text field as there often are leading spaces

**Comment by phillipoertel** [comment]
So here's how I trie to "deduplicate" the organizations in Beekeeper, i.e. merge multiple entries in beekeeper into one in the new database:

If one of the following text snippets was found in the organization's name, the data is taken from the table mentioned above it, id of the record behind the name.

Example: All entries where the organization name was
"Wagnis eG"
"wagnis eG"
"wagnis EG" or
"Wohnbaugenossenschaft wagnis eG"
were merged into one entry in the new database. 
The data for that entry new was taken from the table account_new, from the row with id 70069.

* data taken from the table account_new:

```
wagnis:            70069 
Cohaus:            80792
IGEWO:             80583
Hans Fischer GmbH: 80678
BEG Remstal:       80502
```

* data taken from the table kontaktdaten:

```
Parkgelände GmbH:                         624
BEG Remstal:                              775
Diakonie Stetten:                         790
Gemeinde Hallbergmoos:                    777
IFAGE Grundstücksverwaltungs GmbH:        442
Ritter Baukontor GmbH:                    1097
Umbreit, Olé Madrid:                      46
VR Dachau Immobilien GmbH:                894
WEG Hausverwaltung Alte Rommelshauser St: 1070
WHG Wohnungsbau:                          430
Wogeno München eG:                        998
```

Having done that, the following (possible?) duplicate organizations remain:

1. case: organizations with same email address

![dup_email](https://user-images.githubusercontent.com/5188/35153751-1c8cbe66-fd28-11e7-9b07-be014e0f5e41.png)

2. case: email addresses which are present in the database on person and non-person entries:

```
Ralf.schroeder@gmail.com
Vertragsmanagement@rng.de
a.bock@ich-hab-bock.de
a.heinrich@weissflogheinrich.de
a.miethe@stwwn.de
al@leonhardarchitekten.de
ansprechpartner-datenaustausch@sw-netz.de
bad_sulz@kabelmail.de
bauwesen@hallbergmoos.de
buero@wagnis.org
datenaustausch.vertrieb@swm.de
edm.bnnetze@energiexchange.de
eduard.tiede@stadtwerke-schorndorf.de
erdlekh@erdlekh.de
info@BEG-FS.de
info@christoph-eiser.de
j.fellner@stadtwerke-landshut.de
jan.bohne@lsw.de
joachim.bobert@new-netz-gmbh.de
lieferant@stw-freising.de
lieferantenwechsel@enercity-netz.de
m.schabl@isarwatt.de
mail@hgschreck.de
mar_s1@gmx.de
marktpartner@stromnetz-hamburg.de
mattauch@beg-remstal.de
netzbilanzierung@netz-leipzig.de
netzkunden@stromnetz-berlin.de
netznutzung-hb@wesernetz.de
netznutzung@e-dis.de
netznutzung@lew-verteilnetz.de
netznutzung@peissenberg.de
netznutzungsmanagement@syna.de
netzvertraege@bayernwerk.de
olaf.nimz@stadtwerke-kaltenkirchen.de
re@discovergy.com
sdammann@stadtwerke-einbeck.de
ssge@telta.de
stefan.maeder@stadtwerke-witzenhausen.de
t.brumbauer@wogeno.de
team@thies-hahn.de
tim.warnke@gmx.de
ulrich.haushofer@gmx.de
unknown@unknown.de
versorgerwechsel@lichtblick.de
vertragsmanagement@avacon.de
vertragsmanagement@mitnetz-strom.de
w.heller@stadtwerke-wedel.de
```

3. case: phone numbers which are present in the database on person and non-person entries:

To make the numbers comparable, I removed all non-numerical characters as well as leading 0049 and 49.

```
0000000
002214746571
0024516246389
0087114362076
015122332189
01712044552
01792441663
0240870945420
02432907969
030492023315
03051503782
03361702244
03411216080
040396175
040558991076
04063601200
04103805102
041919360
045217646130
05114301788
0535112333223
053611893630
055425005155
055619422227
0611205550
06931072621
0711218583706
07151131322
071814825653
0718196450407
0761888882274
080417956176
08115522440
08161183164
08161872727
081656479117
081713449702
08803690240
08856602111
08923614644
08936036090
08954444859
08954643217
08989057180
089890571820
089890571824
0921507404575
09412017128
```
