### ISSUE TITLE
implement rubocop setup

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#138]
**PR**
https://github.com/buzzn/core/pull/1388

**User story**

Let's keep the codebase clean and consistent because otherwise: https://pragprog.com/the-pragmatic-programmer/extracts/software-entropy

As a developer
I want a setup for a consistent coding style 
to simplify the PRs. 

---

**Definition of done**

- [x] select minimum set of rules 
- [x] CI fails when rubocop rules don´t pass 

---
**Technical details**

_Backend_

- [x] configure rules given below
- [x] disable all others
- [x] set rubocop up in CI
- [x] add list of plugins to documentation (Emacs, Sublime, Atom), how to run it locally

Rules:

- [x] quotes --> " when string is evaluated, ' when not
- [x] use collect instead of map
- [x] trailing whitespace --> not Ok
- [x] method definitions ---> def foo(arg1, arg2); foo("arg1", "arg2")
- [x] blank lines between methods: exactly one
- [x] private statement: ~~private :name_of_method~~ --> private statement in class --> not possible
- [x] spacing around brackets --> use most common rule

**Comment by phillipoertel** [comment]
Here's how to setup rubocop for your editor https://github.com/buzzn/core/tree/add-rubocop#set-up-rubocop

**Comment by evaklopp** [comment]
closing because it is done. Thanx @phillipoertel
