### ISSUE TITLE
Fix broken "cold" links

### ISSUE THREAD

**Issue by scsirdx** [buzzn/scrum#152]
**PR**
- https://github.com/buzzn/admin-app/pull/266

---

**User story**

As a user
I want working links right after app  start.

---

**Definition of done**

- [x] Links are working after Cmd+R
- [x] Deeply nested data loaded after Cmd+R

---

**Technical details**

_Frontend_

- [x] Handle cold start ( _status: null ) correctly.

**Comment by evaklopp** [comment]
@scsirdx I still have this case, that I´m on the PT-page (overview), clicking on a register (Zählwerk) and get linked to the system-setup page. 
If I go back to the PTs and click again (no matter the same or different register), I get linked correctly but see two 404-messages ( I can´t remember what you requested)

**Comment by evaklopp** [comment]
Hey @scsirdx , yeah, you solved the issue with the link, no everything works fine! Great! THe only thing is, that I still get 404 errors on some groups (e.g. Cherubinistraße) if I click on a register from the pt-page. But it opens the correct register page. Does this belong to this story?

**Comment by scsirdx** [comment]
@evaklopp No.

**Comment by evaklopp** [comment]
Great job @scsirdx thanx for solving this issue! Closing!
