### ISSUE TITLE
As a Pho, I want to import and view all real meters with their registers

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#2]
PR: 
- https://github.com/buzzn/admin-app/pull/252
---
**Story:**
As PhO, I want to import and view all real meters and registers from BeeKeeper into Admin App, so I can verify technical setup for my group.

---
**XD**
 - [x] register and meter list: https://invis.io/J6ENAO22A#/265627583_Desktop_HD_-_System_-_Register_List

---
**Definition of done**
- [x] For each group, all real **meters** are imported
- [x] each meter has values as outlined in the data mapping XLS sheet for this story.
- [x] For each meter, all included **registers** are imported
- [x] each register has values as outlined in the data mapping XLS sheet for this story.
- [x] all registers are labeled correctly (see logic below)

**Excluded**
- The bubble chart shows all consumption registers and the production registers correctly; also in Display App
- All registers that receive data from Discovergy are linked correctly with a broker (new story #29).
- import of historic readings
- link to current and historic PT contracts
- new: import manufacturer name correctly (currently only "Easymeter" or "Other")
- new: sequence number. To verify if we can really reassign them or if we need to import the exact BK numbers
- new: reliably exclude virtual registers
- new: set CONSUMPTION_COMMON correctly after data problems have been clarified
- new: maybe fix the incorrect zählwerk.kennzeichnung of the power generation registers automatically

---

**Technical details**

_Frontend_

- [x] list of **registers** which shows these attributes: 
  - [x] register name (linked to register details)
  - [x] meter serial number (attribute "product_serialnumber", linked to meter details)
  - [x] direction
  - [x] label
- [x] use `group?include=meters[registers]` endpoint to get the data. 

_Backend_

- [x] set meter group
- [x] set register name
- [x] set meter product serial number
- [x] set type (based on direction)
- [x] assign every register to the correct meter
- [x] set label: 
  - [x] most labels already mapped in msb_zählwerk_daten.rb
  - [x] new register label 'PRODUCTION_WATER' and 'PRODUCTION_WIND' (explained in https://github.com/buzzn/scrum/issues/2#issuecomment-344638661), and demarcation labels
  - [x] assign (new) register label 'CONSUMPTION_COMMON' for "Allgemeinstrom". Identified by SN_contracts having the value for EEG_Umlage of "-1".
  - [x] clarify why register "Wachsbleiche 3+5 BHKW Produktion" get incorrectly labeled CONSUMPTION_COMMON
- [x] associate the GRID_CONSUMPTION and GRID_FEEDING registers to the group (ensure label matches)
- [x] ~~remove meters product_name constraint~~ - not present any more
- [x] exclude virtual meters/registers

---

Source tables:
- [msb_gerät](https://buzzn-team.atlassian.net/wiki/download/attachments/102334520/msb_ger%C3%A4t.xlsx?version=5&modificationDate=1511603138337&cacheVersion=1&api=v2)
- [msb_zählwerk_daten](https://buzzn-team.atlassian.net/wiki/download/attachments/102334520/msb_z%C3%A4hlwerk_daten.xlsx?version=4&modificationDate=1511603137307&cacheVersion=1&api=v2)

Data value mapping:
- https://buzzn-team.atlassian.net/wiki/x/mAAq

----

**Latest beekeeper import report (run with SQL dump 2017-11-22)**

https://gist.github.com/phillipoertel/fb4dfbe4a40ea323f77833613164ba30

**Comment by dottorer** [comment]
Technical complexity will be in the correct labeling of registers. Here are some notes:
- we can identify power takers by their contracts and set the label 'CONSUMPTION' for such registers. This can be checked in **minipooldb.minipool_sn.buzznid** which holds the link to the register for the power taker contract.
- the grid connection registers (ÜGZ-Bezug and ÜGZ-Einspeisung) are tracked in **minipool_objekte.bezug_buzznid** / **einspeis_buzznid**.
- the production registers are in **minipool_objekte.sea_1_buzznid / sea_2_buzznid / etc.** whereby we need to determine the type of production by the **sea_1_energieträge**r / etc. (Sonne = label 'PRODUCTION_PV', Erdgas = label 'PRODUCTION_CHP', Heizöl = label 'PRODUCTION_CHP', Wasser = label 'PRODUCTION_WATER'.
- We need to introduce to new labels for register with 'PRODUCTION_WATER' and 'PRODUCTION_WIND'.
- if the **msb_gerät.adresszusatz** on the meter in BK has the word 'Abgrenzung' in it, we need to label it 'DEMARCATION_CHP', there is only one case for 'DEMARCATION_PV'.
- all the rest of the registers should be labeled 'OTHER' and we need to review the content to see if there are false positives in there.

That is the current wisdom on how to assign correct labels. We need to try and refine.

**Comment by dottorer** [comment]
@phillipoertel I now remembered that in our prototype importer we label the registers based on the content of 'kennzeichnung' which is somewhat consistent. This should align with the rules above, which help us identify more specialized registers...

**Comment by phillipoertel** [comment]
@dottorer exactly, we always check the "kennzeichnung" field now, see https://github.com/buzzn/beekeeper_migrator/blob/master/lib/models/msb_z%C3%A4hlwerk_daten.rb#L57-L69

**Comment by dottorer** [comment]
@phillipoertel First cut at possible field mapping directly for Meters is identified now in https://buzzn-team.atlassian.net/wiki/download/attachments/102334520/msb_ger%C3%A4t.xlsx?api=v2

**Comment by dottorer** [comment]
@phillipoertel Updated the data mapping sheets for meters and registers and provided detailed instructions on how we can map columns and derive values. This should be all demystified and doable now, based on my understanding.

**Comment by phillipoertel** [comment]
@evaklopp @dottorer I just pushed a version of the meters and registers (still heavy work in progress), here's Heigelstraße for a preview: https://staging-console.buzzn.io/admin/groups/e9776f92-3acd-42bf-bd12-bbe08db0f474

**Comment by dottorer** [comment]
@phillipoertel this looks great! One thing i noticed was that in the case of a two way meter, the 2 registers appear to not be hooked up to the same instance.

https://staging-console.buzzn.io/admin/meters/17881797-2f01-429b-af5b-6c4ba1fbde55

This meter should have both an IN and an OUT register associated.

I will review the rest later in more detail. Great progress!

**Comment by phillipoertel** [comment]
Hi @dottorer, thanks for the praise. I know the meters aren’t hooked up correctly in case of ZRZ, many other spots are also known todos. So you don’t have to review this already, that wasn’t my intention here. I’ll let you know when I think this story is ready.

**Comment by dottorer** [comment]
Great, just got excited here :-) If you want to discuss the more minute details of data mappings we could connect today after standup to go over your list to ensure we got it all in there...

**Comment by phillipoertel** [comment]
@evaklopp @eharit for inspiration on the German word for "label", these are the values the field can take: https://github.com/buzzn/core/blob/d32fd52224036e0eb0451293621b2221235ee6c8/db/structure.sql#L491-L503

**Comment by evaklopp** [comment]
@phillipoertel wow very good to see all your effort of today! Good process, thanks a lot! And thank you for the hint for the label-Name! Let´s see which german word I choose ;-)

**Comment by phillipoertel** [comment]
@dottorer I currently identify virtual registers by the text "virt" or "vit" (we have typos and abbreviations) in at least one of the fields zählernummer, adresszusatz, zählerHersteller, zählerTyp or berechnetbeschreibungkurz. That rule results in 20 virtual registers. Let me know if that isn't reliable enough.

**Comment by mkristian** [comment]
@phillipoertel this criteria is OK if I look at the serialnumbers imported. an empty serialnumber should not go into the DB as well IMO (one case).

**Comment by dottorer** [comment]
@phillipoertel I think this is as good a logic to identify them as we will get. We might check for anything entered in any of the 4 'berechnet....' fields and ignore those as well. 

For this ticket we simply do not touch the virtual meters and registers and think about how to get them loaded properly. My concern for later is that we will need to have these '**grid_consumption_corrected**' and '**grid_feeding_corrected**' virtual meters in order to subtract the registers that are third party supplied. But I believe it is best to generate these using a different logic and not rely on BK data.

For now your logic above suffices....

**Comment by phillipoertel** [comment]
@dottorer some groups use a virtual register for the grid consumption/feeding register (like Orleansstraße 61 and Häberlstraße 15). Since we don't import virtual registers yet, those groups are displayed as incomplete.

**Comment by phillipoertel** [comment]
@dottorer I don't understand why the grid feeding and consumption registers must be additionally assigned to the group, that's redundant IMHO and always has the potential to go out of sync.
It's clear already just by the register label, and the column/join can be replaced with one line of code:
```ruby
class Group::Base
  def grid_feeding_register
    registers.grid_feeding.first # the registers.grid_feeding scope is auto-generated by Rails since it's one of the values of the label enum
  end
end

**Comment by mkristian** [comment]
@phillipoertel just go replace this like you suggested, as long the completeness check remains intact. it is just not clear when and how we use these registers, dito the reference back from register to the group.

**Comment by mkristian** [comment]
@phillipoertel and we need to make sure we have only one of those grid_xxx register each. so we need to extend the invariant here.

**Comment by phillipoertel** [comment]
@dottorer I think the `minipool_sn.eeg_umlage` is not reliable for assigning the `CONSUMPTION_COMMON` label. Many registers which have an `adresszusatz` containing "Allgemein" have `eeg_umlage` 1, not -1.

**Comment by phillipoertel** [comment]
The register `Wachsbleiche 3+5 BHKW Produktion`also has an eeg_umlage of -1. Is that intended or a mistake?

**Comment by phillipoertel** [comment]
@dottorer while trying to label the "Stromerzeugunganlagen" of our localpools correctly I found some inconsistencies, see below. I assume the `zählwerk.kennzeichnung` hasn't always been maintained and would correct that on import.

I also can't make sense of the column `minipool_objekte.sea_4_buzznid`. It often contains a 60xxx contract number. Checking the msb_gerät for that it's things like "Heizungsstrom" and "Allgemeinstrom". (How) do we need to import this?

```
Häberlstraße 15
--------------------------------------------------------------------------------

Stromerzeugungsanlage 90006/24:
- sea_1_energieträger:             Erdgas
- zählwerk.kennzeichnung:          Bezug
- zählwerk.msb_gerät.adresszusatz: BHKW Produktion

Orleansstraße 61
--------------------------------------------------------------------------------

Stromerzeugungsanlage 90020/22:
- sea_1_energieträger:             Erdgas
- zählwerk.kennzeichnung:          Bezug
- zählwerk.msb_gerät.adresszusatz: VG Technikraum re Zählerschr. BHKW Produktion

Wachsbleiche 3+5
--------------------------------------------------------------------------------

Stromerzeugungsanlage 90039/15:
- sea_1_energieträger:             Erdgas
- zählwerk.kennzeichnung:          Bezug
- zählwerk.msb_gerät.adresszusatz: Wachsbleiche 3+5 BHKW Produktion

Reinmarplatz
--------------------------------------------------------------------------------

Stromerzeugungsanlage 90042/57:
- sea_1_energieträger:             Sonne
- zählwerk.kennzeichnung:          Sonstige
- zählwerk.msb_gerät.adresszusatz: PV Produktion

Am Urtlgraben 15
--------------------------------------------------------------------------------

Stromerzeugungsanlage 90045/8:
- sea_1_energieträger:             Wasser
- zählwerk.kennzeichnung:          PV Produktion
- zählwerk.msb_gerät.adresszusatz: Wasserkraft Produktion

Michaelisstraße 10
--------------------------------------------------------------------------------

Stromerzeugungsanlage 90050/2:
- sea_1_energieträger:             Sonne
- zählwerk.kennzeichnung:          Bezug
- zählwerk.msb_gerät.adresszusatz: PV Produktion

UdE 7
--------------------------------------------------------------------------------

Stromerzeugungsanlage 90053/26:
- sea_1_energieträger:             Sonne
- zählwerk.kennzeichnung:          Bezug
- zählwerk.msb_gerät.adresszusatz: PV Produktion

Marktplatz 1-7
--------------------------------------------------------------------------------

Stromerzeugungsanlage 90086/8:
- sea_1_energieträger:             Erdgas
- zählwerk.kennzeichnung:          Bezug
- zählwerk.msb_gerät.adresszusatz: BHKW Produktion
```

**Comment by phillipoertel** [comment]
Update: maybe PhO can clean up the zählwerk.kennzeichnung before the next import, that'd probably be easier.

**Comment by phillipoertel** [comment]
@dottorer @evaklopp for various reasons (see above :-)) some fields aren't imported 100% correctly. I updated the "excluded" list of the DoD so we know what's still missing/left to do.

**Comment by phillipoertel** [comment]
@evaklopp the story is now ready to test on staging.

**Comment by evaklopp** [comment]
WoopWoop!

**Comment by mkristian** [comment]
@dottorer these virtual meters are most probably already defined on Discovergy, so we need a way to keep Discovergy and our side in sync (at a certain point in time)

**Comment by dottorer** [comment]
@phillipoertel You found our hack! Pho and I talked about when we import the SN contracts and there is a gap in the timeline for a register, we need to create a new interim contract for the register. The customer for this 'gap contract' where a flat might have been empty is to be paid by the Hausverwaltung or the group owner. To know which party in the group is that 'default fallback customer' we used the only free field in BK we could find and stored the '60003/2' in it to reference a customer.

We used it since there was never a 4th generation device.

**Comment by phillipoertel** [comment]
@evaklopp a detail the group "Am Urtlgraben" only has water-based energy production ... we could use an icon for that. This info may have to be added to the API as well, asking @mkristian 
.
![bildschirmfoto 2017-12-01 um 10 49 29](https://user-images.githubusercontent.com/5188/33477294-77381294-d685-11e7-8363-ec3c05bd44d5.png)
