### ISSUE TITLE
As Pho I want to see and edit the visibility status of a group 

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#23]
PR: 
- https://github.com/buzzn/admin-app/pull/242
---
**Story**
Pho I want to see and edit the visibility status of a group like it is signed in the contracts. 

---
**Definition of done**
- [x] integrate the booleans in design
- [x] view the visibility settings of the group in buzzn.com (admin app) ~~according to the signed contract~~
- [x] edit visibility settings of the group

Not in this ticket:
- fix 401 for registers endpoint for display-API
---
**Technical details**

- [x] create design
- [x] create inline editable field for booleans
- [x] style them (switches)

---
**XD**

https://invis.io/D5EJM1ZTP#/264824835_Ticket_-1_-4_Groupview_empty
and
https://invis.io/BXEFBA2EF#/262879736_WF_Group_Overview_V2

**Comment by phillipoertel** [comment]
FYI the four visibility settings are: 
show_object boolean
show_production boolean
show_energy boolean
show_contact boolean

**Comment by dottorer** [comment]
This is what we currently track in our LCP contracts:
![image](https://user-images.githubusercontent.com/14217285/32885023-85ec6d46-cabc-11e7-8714-3ee353909e12.png)

**Comment by phillipoertel** [comment]
Some acceptance criteria:
- the display app respects the visibility settings
- the settings are displayed in the admin app

**Comment by evaklopp** [comment]
@scsirdx short question: if I edit the booleans now, do I allready changing something in the backend data? And are the currents setting already the settings which are in the contracts? Not, as far as I understood, right?

**Comment by dottorer** [comment]
There is nothing to import from BK so all groups will have ‚off‘ as default. Any changes made however should be persisted.

**Comment by scsirdx** [comment]
@evaklopp Yes, requests are real.
Not sure about contracts.

**Comment by evaklopp** [comment]
Hooray ;-)
