### ISSUE TITLE
As Pho I want to import and see all the prices belonging to a group.

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#27]
**PR**
---

**Story**
As Pho I want to import and see all the prices belonging to a group

---
**XD**
- [ ] check designs

**DoD**
- [ ] show current prices
- [ ] make sure that

exclude: 
- price history

**Comment by phillipoertel** [comment]
FYI this is the data we track so far:
    name
    begin_date
    end_date
    energyprice_cents_per_kwh
    baseprice_cents_per_month

**Comment by dottorer** [comment]
@evaklopp We need to line this up with #123 , seems duplicated.

**Comment by evaklopp** [comment]
closing, will be solved in #123

**Comment by evaklopp** [comment]
closing, will be solved in #123
