### ISSUE TITLE
As a Pho, I want to import data sources for real registers

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#29]
PR: 
- https://github.com/buzzn/core/pull/1308
- https://github.com/buzzn/core/pull/1310
---
**Story:**
As PhO, I want to import data sources for all real registers from BeeKeeper into Admin App, so I can verify see live power data for the register.

---
**XD**

- [x] display power from Discovergy on the register detail page
https://projects.invisionapp.com/d/main#/console/12205665/265812600/preview

---

**Definition of done**
- [x] All registers that receive data from Discovergy are linked correctly with a broker
- [x] ~~see the correct total consumption in kWh (used energy) on the register~~ -- out of the scope of this ticket, please see https://github.com/buzzn/scrum/issues/29#issuecomment-347811347 for details
- [x] new DoD: show the current, live power of the register (received via Discovergy) based on Pali's design

---
**Technical details**

_Frontend_

- [x] show register energy consumption on register details page (PG)

_Backend_

- [x] specify which endpoint to use for register energy data (optionally implement it). Start with current ticker endpoint.
- [x] remove Discovergy username/password from source code and DB table (get it from environment)
- [x] configure local and staging envs to use Discovergy username/password from env
- [x] remove Discovergy OAuth token from table, store in memory only (will be renewed on each deploy)

**Beekeeper mapping info (if required)**

https://buzzn-team.atlassian.net/wiki/x/OIAZBg
Source tables:
- msb_gerät
- msb_zählwerk_daten

Data value mapping:
- https://buzzn-team.atlassian.net/wiki/x/mAAq

**Comment by phillipoertel** [comment]
@evaklopp @dottorer we noticed in the standup that requirements of this story were in conflict -- the user story said to display **power**, but the definition of done said to display **energy**. According to @mkristian displaying **energy** requires significant effort. So, since no one of you was around to clarify, we took the simplest path and decided to display **power**, in a simple way, since the final UX/design for it wasn't ready, yet.

**Comment by dottorer** [comment]
@mkristian What is missing for this story to be testable? It has been out there for a while...

**Comment by mkristian** [comment]
the meters needs to be there so one can see the ticker

**Comment by dottorer** [comment]
@mkristian @evaklopp Capturing the discussion from slack about what to show. I left a comment in InVision as well: https://projects.invisionapp.com/d/main#/console/12205665/266641260/comments/90478535 

If we show power here, the unit is kW or Watt. But since this for Pho, I am not sure he is interested in the power draw at this very moment (or would be allowed to even see it), but he is more interested in the latest energy sum of the register (i.e. 345,6 kWh). The energy sum is much less vivid and can be refreshed once on opening the page. This would be called "Zählerstand".

FYI  - Discovergy shows both values: current power and meter "Zählerstand". We also get both values in the APi call, so it would be possible to render both, one looking like Pali's design right now and maybe add a counter like view

![image](https://user-images.githubusercontent.com/14217285/33704288-300ab8c6-db2c-11e7-9c73-f11a87c8a2fe.png)

**Comment by phillipoertel** [comment]
@dottorer the issue is also not complete because technical things are not done yet. If we don't implement them, we're building up technical debt.

**Comment by mkristian** [comment]
DoD says we show power with this story and not energy as originally stated. so is the UI implemented as well. to switch back to energy is to start all over again.

this point gets elaborated in  https://github.com/buzzn/scrum/issues/62 and there we shall switch from power to energy or both or whatever

**Comment by mkristian** [comment]
@evaklopp on staging the group `Bahnhofstr. 21` shows the WATT ticker nicely. All in all there are registers in other groups which are not discovergy which will show `0` and all `Zwei-Richtungs-Zähler` are not working correctly and could return negative values.

for reference you can find the respective meter on https://my.discovergy.com/dashboard by searching the serial-number in the meter list. (maybe @dottorer can show you or could give you access to this portal).

**Comment by evaklopp** [comment]
@mkristian cool, I found it! And I found many others which show positive data! Nice!

**Comment by evaklopp** [comment]
As far as I could see: HOOORAY! THank you Kristian!
