### ISSUE TITLE
As a developer, I want to have my Staging System running on Heroku

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#35]
PR: https://github.com/buzzn/core/pull/1290

---
**Story:**
As a developer, I want to have my Staging System running on Heroku so I have a stable system for development.

---
**Definition of done**

- [x] Core (https://staging-admin.buzzn.io) is accessible on Heroku and shows last successful master build
- [x] performance and reliability is good
- [x] uptime monitoring via ping linked to Slack
- [x] Console (https://staging-console.buzzn.io ) is accessible on Heroku

**excluded from this first sprint:** 
- auto-deploy of PRs
- no sidekiq on Heroku (worker and ui)
- NewRelic
- Swagger UI no longer supported, leave behind
- ignore clockwork (used for cron jobs)
- switching application to run in production environment

---
**Technical details**
- [x] **Core app** connected to Heroku
- [x] rename repository to Core (from buzzn)
- [x] open new account on Heroku for admin@buzzn.net - RS
- [x] "git push heroku" works
- [x] postgres in Heroku
- [x] Reddis on Heroku
- [x] current ENV vars correctly set in Heroku, manual ok
- [x] example data loaded
- [x] MongoDB is running on Heroku
- [x] **Console** moved to Heroku as second system, link DB
- [x] CloudFlare points to Heroku endpoint (for core and console)
- [x] ~~connect AWS-S3 for file access~~ (will configure it when we fix the user images)
- [x] enable Slack integration
- [x] enable SSL certificate for core and console
- [x] remove docker configs from repos
- [x] update the git & build info in https://staging-core.buzzn.io/health
- [x] document new deployment
- [x] delete old core/console images on hub.docker.com 
- [x] retire Digital Ocean deployment and disable account / payment data
- [x] import latest Beekeeper SQL dump
- [x] fix test/build (MongoDB connection issue?)
- [x] share deployment info with developers
- [x] test availability alert (Slack message when down?)

**Comment by phillipoertel** [comment]
@evaklopp @dottorer this is done IMHO, please test and move to done!

**Comment by dottorer** [comment]
All seems peachy - a job well done and glad we're finally moved!

**Comment by evaklopp** [comment]
@dottorer @phillipoertel  WHo takes care of the excluded elements in this ticket?

**Comment by phillipoertel** [comment]
@evaklopp good that you check :-) The excluded elements are not needed for the features we're actively using/building now. Once we have user stories that do, we'll invest the work to reenable them. 
So it's not necessary to track those excluded elements -- we'll automatically be reminded of them once we need them again.
