### ISSUE TITLE
As PhO I want to see my all my groups in tiles.

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#39]
**PR**

---
**Story**
As PhO I want to see my all my groups in tiles, so I can see high level info at one glance.

---
**XD**
- see design here: https://projects.invisionapp.com/d/main#/console/12205665/258120359/preview
- [x] design review
---
**DoD**

- [x] a tile consists of group name, group image, icons for power generation source(s)
- [x] Default group image if none is uploaded
- [x] Tiles are ordered alphabetically by group name
- [x] space for additional analytics underneath the group image: empty values for the moment
- [x] additional analytics underneath the group image: Total consumption for current day in kWh ("Verbrauch" / "Consumption")

- [x] Clicking on a tile (whole tile) opens up the detail page for that group.
- [x] Hover over highlights tile for clicking; shows 'View Details' button
- [x] From the group list view, clicking on the "List icon" switches back and forth between tile and list view (more in #43).

excluded:
- scores for sufficiency, etc.
- drag & drop of group tiles (and persist of order) to improve order or another ordering algorithm.
- upload of custom group image
- Total production for current day in kWh ("Produktion" / "Production") 
- additional analytics underneath the group image: Daily percentage value for autarchy as amount of consumption covered by self generated energy ("Autarkie" / "Self sufficiency").
---

**Technical details**
- [x] analytics information always have the value "--" since we don't get real data from the backend yet.

**Comment by eharit** [comment]
@evaklopp design updated, please review.

**Comment by evaklopp** [comment]
hey @scsirdx Design review is done, designs are ready ;-)

**Comment by evaklopp** [comment]
@scsirdx cool, 3 things: 
1. can you do three little translations on the tile please? 
production: "Produktion", Consumption:"Verbrauch", Autarchy: "Autarkie". 
2. If I clicked on a tile, and next action is clicking on the "browser back" chevron or on the BUZZN logo to get back to the overview, I always get directed to the list view of the groups. Should always be the last chosen view (tiles OR list). Is that possible or too big for this sprint?
3. last and I think it is more an design issue: can we make the defualt picture smaller, so that the BUZZN-flash is not overlapping with the Group-names? It is not very important, so if this is a big issue don´t do it.

**Comment by scsirdx** [comment]
@evaklopp 1 and 2 done. But i cant find a proper image for N3.

**Comment by evaklopp** [comment]
Yeah!
