### ISSUE TITLE
As a Pho, I want to import and view Group Owners from BK 

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#4]
PR: 
- https://github.com/buzzn/admin-app/pull/244
- https://github.com/buzzn/core/pull/1295
- https://github.com/buzzn/core/commit/8fa92051744bb184acb7d9131ad3a39629106b86 (missed making a PR for this)
- https://github.com/buzzn/core/pull/1296
- https://github.com/buzzn/core/pull/1299
- https://github.com/buzzn/core/pull/1300
- https://github.com/buzzn/core/pull/1301
---
**Story:**
As PhO, I want to import Group Owners data from BeeKeeper into buzzn.com, so I can view and verify it.

---
**XD-Preparation**

- [x] add missing fields Bank account, Customer number (former "Vertragskontonummer")
- [x] add "organisation" and a 
- [x] link to organisations like the ÜNB/VNB etc 
- [x] add "Contracts" to the group part (4 different possible Mpo, Lgp, Pg, Pt. + n pt contracts)
- [x] clustering of the information in 3 areas: "Group", "Groupowner" where data is editabel and "Group overview" which links to different topics of the group. 

Wireframes ready: 
here is the link: 
unfilled page: https://invis.io/D5EJM1ZTP#/264824835_Ticket_-1_-4_Groupview_empty 
filled with data: https://invis.io/F8EJM26WC#/264824834_Ticket_-1_-4_Groupview_filled

proposal of how filling in data: 
https://invis.io/3KEJM2IQA#/264824836_Ticket_-1_-4_Groupview_Statues_Group and following screen in InVision. 

- [x] adjust Design
Link to the updated design: https://projects.invisionapp.com/d/main#/console/12205665/262879736/preview 

---
**Definition of done**
- [x] All local groups have Person or Org and contact as owner
- [x] Owners have address, emails and bank account
- [x] Owners have a customer_number
- [x] Orgs as owners have contact person with address and email, phonenumber
--- 

**Technical details**

_Case person_
- [x] import person base data and link to localgroup correctly
- [x] import person bank account
- [x] import person address

_Case org_

- [x] import organization base data and link to localgroup correctly
- [x] import organizations bank account
- [x] import organization address
- [x] import organization contact person (incl. address)
- [x] assign org bank account (PO)
- [x] method to get org bank account (PO)
- [x] export org bank in API (PO)

_General_

- [x] move owner role check from completeness to invariant
- [x] Design
- [x] Build frontend for organization section of Stromgeber (hide if owner is person)
- [x] Build frontend for ansprechpartner section 
- [x] Build frontend for kundennummer section 
- [x] Build frontend for bankkonto section 
- [x] Add group with owner === 'organization' and organization contact (and addresses/bank accounts)
- [x] Clean up remaining non-IBAN Bank accounts, get new dump after PhO is done
- [x] Look up bank name by IBAN/BLZ (clarify)
- [x] import customer number from beekeeper (PO)

Excluded:
- Übersicht section
- Konto hinzufügen

----

https://buzzn-team.atlassian.net/wiki/x/OIAZBg
- Source tables: 
-- minipooldb.minipool_objekte
-- buzzndb.account_new
-- buzzndb.kontakt_acc
-- minipooldb.kontodaten

**Comment by mkristian** [comment]
@evaklopp we are importing a lot of addresses. in our DB there is the field 'state' which rarely set and it is redundant in the sense that if can be looked up via the zipcode. and your UI sketch it does not even gets displayed.

in order to keep things simple I would like to remove this field from our DB altogether. can I add this to this issue.

**Comment by evaklopp** [comment]
Hey @mkristian from my point of view we don´t need it, because as far as I know we have customers in germany only. But I don´t know if there are any other objections, @dottorer ?

**Comment by phillipoertel** [comment]
+1 for removing it. FYI @dottorer also already wondered about it when we compiled the organization addresses.

**Comment by dottorer** [comment]
@evaklopp Likely YAGNI. We can either remove it or leave it in the model only for the time when we get international addresses. But for that case, I'd rather add it with form requirements.

**Comment by scsirdx** [comment]
@phillipoertel Current seeds have localpool with owner === 'person'
We need another one with owner === 'organization' and contact.

**Comment by scsirdx** [comment]
We can't display proper bank account on this page. Because it's unclear which one from the owners bank accounts is related to this group.
@dottorer @evaklopp

**Comment by dottorer** [comment]
Per Pho this was supposed to be the bank that the powertakers have to pay the power giver. So it should the bank associated with the LPTc for the contractor (the Wolfgang).

In our model, it would be possible to assign different banks at any contract. In reality the contract for payments from the PTs to the PG should only be one. This is a possible issue.

From a Pho perspective , if we were to show the bank associated with the LGPc (so the bank that Buzzn charges Wolfgang for our services), we would have a singular bsnk account.

Note that almost always there is only one bank account in play for all of this. We have a slightly overflexible model which cause more confusion than good.

@evaklopp please clarify with Pho how to proceed and what the best model for bank accounts would be.

**Comment by mkristian** [comment]
need to summarise @dottorer :
* there is one bank_account for the powertakers to pay Wolfgang
* there is one bank_account for Wolfgang to pay buzzn

currently we have bank_accounts (note the plural) on all organizations and persons and contracts can pick one for the customer and one for the contractor.

@dottorer @evaklopp let's slim down the whole thing to what we need !

**Comment by mkristian** [comment]
@dottorer this means 
* add `the_bank_account` to group which picks one from the owners bank_accounts.
* remove all customer_bank_account and contractor_bank_account but keep customer_bank_account  on metering_point_operator contracts and localpool_processing contracts.

sounds good. for this issue I could add this missing association for the first point and the rest we make when we reach the contract imports.

waiting then for some feedback and/or OK from @evaklopp

**Comment by dottorer** [comment]
:+1:

**Comment by eharit** [comment]
Added extra fields according to @evaklopp 's last instructions, we with @scsirdx need a shorter (and German) label for 'Legally Responsible Person'.

**Comment by mkristian** [comment]
@eharit not sure where the Legally Responsible Person comes into play as `Contact Person` != `Legally Responsible Person` and there is only a import of the contact at the moment.

**Comment by evaklopp** [comment]
@eharit and @scsirdx please use "verantwortlich" for Legally Responsible Person' for the moment. thx

**Comment by evaklopp** [comment]
@eharit @scsirdx I found a much better word for this legal responsible person: "Vertreter" or, if we have enough space: "gesetzl. Vertreter". Thank you for changing.

**Comment by dottorer** [comment]
@phillipoertel Once we have the customer_number imported from BK, can this be set to 'ready to test'?

**Comment by phillipoertel** [comment]
@evaklopp the story is ready to test on staging.
- here's a localpool where the organization is owner: https://staging-admin.buzzn.io/localpools/62aad355-89ca-40e2-98a1-84ebfbbf2964/settings
- here's a person owner: https://staging-admin.buzzn.io/localpools/610e317a-ba6c-4160-ad95-79d0629569b8/settings

**Comment by phillipoertel** [comment]
For your / PhO's information: these are the completeness validations for the latest beekeeper dump (date 2017-11-22):

```
localpool cherubinistr-4-8:
	bank_account: ["must be filled"]
localpool pariser-strae-11:
	bank_account: ["must be filled"]
localpool oberlnderstrae-20:
	bank_account: ["must be filled"]
localpool marktplatz-1-7:
	electricity_supplier: ["must be filled"]
localpool memminger-str-16:
	electricity_supplier: ["must be filled"]
	bank_account: ["must be filled"]
localpool helbigstrae-16:
	distribution_system_operator: ["must be filled"]
	transmission_system_operator: ["must be filled"]
	electricity_supplier: ["must be filled"]
	bank_account: ["must be filled"]
localpool bismarckstr-4:
	distribution_system_operator: ["must be filled"]
	transmission_system_operator: ["must be filled"]
	electricity_supplier: ["must be filled"]
localpool blumenthalstr-19:
	distribution_system_operator: ["must be filled"]
	transmission_system_operator: ["must be filled"]
	electricity_supplier: ["must be filled"]
localpool kopperpahler-allee-14:
	distribution_system_operator: ["must be filled"]
	electricity_supplier: ["must be filled"]
	bank_account: ["must be filled"]
localpool cerveteristrae:
	distribution_system_operator: ["must be filled"]
	electricity_supplier: ["must be filled"]
	bank_account: ["must be filled"]
localpool kaspar-spth-str-18:
	electricity_supplier: ["must be filled"]
	bank_account: ["must be filled"]
localpool hrnleweg-6:
	electricity_supplier: ["must be filled"]
	bank_account: ["must be filled"]
```

**Comment by dottorer** [comment]
Reviewing some inconsistencies on org.contact_person.address...stay tuned!

**Comment by dottorer** [comment]
@phillipoertel @mkristian Research for addresses of group owners.

Example: The local group **'Heigelstr. 27B'** has the following in the `minipooldb.minipool_objekte` :
- adress_id = 923 (Heigelstr. 27b, etc.)
- adress_id_kontakt = 924 (Ammerseestr. 8, etc.)
- kontaktdaten_id = 824 (Ralf Schroeder)

The source tables for the addresses are the `minipooldb.adresse` table. This lines up with:
- kontaktdaten_id = 824 to be looked up in `minipooldb.kontaktdaten` which points to person Ralf Schroeder, which should live at the adress_id_kontakt of 924 above.

Also, the group owner is the vertragskontonummer = 80674 which points to `buzzndb.account_new` and is correctly linked to "DAD Solar" with its own address on this table.

The contact person for this org is to be found in `buzzndb.kontakt_acc` where the fibunr is 80674. There we also find 'Ralf Schroeder, Ammerseestr. 8, etc'. 

Now, there are two ways to get to the address of the contact person. It seems that the correct path is to go via account_new->kontakt_acc. The other way seems to be an old path for a contact person directly on the group itself in BeeKeeper.

In any case, we should see in the UI that the contact person for an org has a different address.

**Comment by phillipoertel** [comment]
@mkristian could you take care of the correct address import?

**Comment by mkristian** [comment]
localpool address is from minipooldb.minipool_objekte
person address is from buzzndb.kontakt_acc
organization address is from buzzndb.account_new

the last two are mostly the same beside some typos: Localpool Ligsalzstr. 46

**Comment by mkristian** [comment]
another example with really different addresses: Localpool Bismarckstr. 4

**Comment by mkristian** [comment]
does it also make sense that the address of the contact person of an organization is the same as organization itself !?

**Comment by dottorer** [comment]
@mkristian In many cases this makes sense. The contact person usually works for the organization operating the group. So a likely scenario is group.address != org.address but org.address ==contact_person.address.

Does this help?

**Comment by mkristian** [comment]
it helps. group.address != orga.address is usually the case. and we do have at least one distinguished  case where org.address != org.contact.address 

example:
Localpool Ligsalzstr. 46
Localpool Bismarckstr. 4

**Comment by evaklopp** [comment]
Hooray, finally #4 gets closed 👍
