### ISSUE TITLE
As PhO I want to get linked to the start page if I click on the BUZZN logo

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#41]
**PR**
- https://github.com/buzzn/admin-app/pull/245

---

**Story**
As PhO I want to get linked to the start page if I click on the BUZZN logo. 
--- 

**DoD**
- [x] link BUZZN-Logo to the my groups page https://staging-admin.buzzn.io/localpools 
- [x] make sure that the chosen group-view (list or tiles) is the same as chosen before.

**Comment by scsirdx** [comment]
@evaklopp There is no tiles view, so the second part is irrelevant right now.

**Comment by evaklopp** [comment]
@scsirdx yes you are right, there is no tiles view at the moment, but we will have sooner or later.

**Comment by phillipoertel** [comment]
Pulled into the sprint because Pavel is running out of work to do.

**Comment by evaklopp** [comment]
@scsirdx now we have the tiles view, maybe you can finish this ticket? ;-)

**Comment by evaklopp** [comment]
yeah!
