### ISSUE TITLE
As PhO I want to see all the details of the  meter

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#48]
**PR**
- https://github.com/buzzn/admin-app/pull/258
---
**Story**
As PhO I want to see all the details of the meter

**XD prep**
- [x] make detail screen, 

see in InVision here: 

https://projects.invisionapp.com/d/main#/console/12205665/266130207/comments

- sent data from the dso"

---
**DoD**

import meter details which consists of parts: 
- [x] serial number as page title
- [x] header with most important data: Manufacturer name, product name, type (real/virtual), converter constant
- [x] the readings of the register of the meter. can be one or two. 
- [x] display the readings in an accordion like in #66 
- [x] meter details: manufacturer name, manufacturer description, productname, ownership, build year, calibrated until, converter constant, Installationsort/location of the meter, data source, sent data DSO, direction number, section, sequence number
- [x] edifact information 
- [x] the fields should be displayed / ordered according to the design

excluded: 
- meter connection status (green/red, grey when it isn´t a smart meter), is part of #61 

**technical details**

_Frontend_

- [x] implement page as listed in DoD
- [x] details of value mapping for edifact codes: https://buzzn-team.atlassian.net/wiki/spaces/DEV/pages/2752664/Flow+View+and+Edit+Real+Meters+and+Registers

_Backend_

- [x] API: add data source to meter endpoint

**Comment by evaklopp** [comment]
Hey @eharit reviewed it, I think we should talk about it with PhO this afternoon, especially about the order of things. Thanks for doing the first approach!

**Comment by evaklopp** [comment]
@eharit how fare are you with this story? Can you adjust this screen according to the sketch I provided after the discussion with PhO? https://projects.invisionapp.com/d/main#/console/12205665/266416409/preview

**Comment by dottorer** [comment]
@mkristian Please expose manufacturer_description, location and data source on the API for meters. Also, please update DoDs as things get completed.

**Comment by mkristian** [comment]
`data source` is actually a field on register and we can have two registers and then this is not well-defined. I can make a virtual `data-soruce` filed but currently this is error prone as not all cases produce reliable results.

**Comment by scsirdx** [comment]
So we're omitting  section and dataSource?
@evaklopp

**Comment by scsirdx** [comment]
Ok, as a temporary solution we can use datasource from the 1st register for the meter.

**Comment by phillipoertel** [comment]
i18n for the data source identifiers:
- standard_profile => Standard profile / Standardlastprofil
- discovergy => Discovergy / Discovergy

**Comment by scsirdx** [comment]
sent data DSO omitted (according to design).

**Comment by evaklopp** [comment]
Great work Pavel and team!
Last thing: please translate the headline "meter details" to "Zähler Details". 
Thank you.

**Comment by dottorer** [comment]
@evaklopp I have done the i18n already and it will be pulled in the next deploy. I think we can close it out...

**Comment by evaklopp** [comment]
thanx for the great work all, closing this ticket, yeah!

**Comment by phillipoertel** [comment]
@evaklopp @dottorer I noticed that the attribute `manufacturer_description` is not yet displayed in the header. Without it, it's impossible to identify some of the non-EasyMeters.

Here's a suggestion for the display logic
```ruby
if is_easy_meter?
  manufacturer_name + product_name
else
  manufacturer_description + product_name
```

This would result in the following meter headers. They are screenshots from staging, my annotations/change in red.

If we combine the manufacturer name and model into one continuous text, we can save some real estate in most cases.

![easymeter](https://user-images.githubusercontent.com/5188/34049107-75293d70-e1b6-11e7-94db-2dfe92148e56.png)
![other iskra](https://user-images.githubusercontent.com/5188/34049108-7545c486-e1b6-11e7-8b06-5ba6d43e3896.png)
![other - edis](https://user-images.githubusercontent.com/5188/34049109-757d595a-e1b6-11e7-8c39-d1f1043afaa1.png)

**Comment by evaklopp** [comment]
Hey @phillipoertel sounds clear and logic to me. But we don´t need to safe real estate in this case. I think we can use your logic - but keep the labels and the place where they are. So if there is no manufacturer name, it should be the label "Herstellerbeschreibung" / "Manufacturer description" instead of manufacturer name. If there is no productname, the field stays empty. 
Will there ever be the case, that we have all three fields? Manufacturer name + description+productname?

**Comment by phillipoertel** [comment]
> Will there ever be the case, that we have all three fields? Manufacturer name + description+productname?

Yes, we have that case for most of the "Other" manufacturers,  but then we don't show the text "other", but the manufacturer description. Here are the stats/counts for all combinations:

<img width="549" alt="bildschirmfoto 2017-12-18 um 22 11 22" src="https://user-images.githubusercontent.com/5188/34128275-6d0666fe-e440-11e7-98ff-596af9a8717c.png">

**Comment by evaklopp** [comment]
@phillipoertel if we basically show "other" when we don´t have a manufacturer name, we can treat it like there is none. So we never have the case that we have all three fields filled in with propper data. Than let´s go for your propposal to show the manufacturer description instead of the manufacturer name if there is no name. Does It makes it easier if we change the label in FE basically to "manufacturer" and fill in the information we have, either the name or the description. Does this makes sense? 
If we can do it like this, please keep the spacings for the name/description and the productname as it is in the design.

**Comment by mkristian** [comment]
if we go with `manufacturer` as proposed by @evaklopp it makes sense to hide this complexity on the server and just deliver a `manufacturer` using the data from DB fields as proposed here.
