### ISSUE TITLE
As Pho, I want to see all my energygroups in a list to see all and navigate easily between the groups

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#5]
PR: 
- https://github.com/buzzn/admin-app/pull/236
- https://github.com/buzzn/admin-app/pull/238
- https://github.com/buzzn/admin-app/pull/240
---
**Story:**
As PhO, I want to see all my energygroups in a list to have a quick overview and navigate easily inbetween the groups

---
**Definition of done**

- [x] I see all current energygroups in a list
- [x] sorted A-Z (top A) by the group name
- [x] the list shows groupimage, groupname, source
- [x] if clicked on a groupname, I get linked to the group-view-site like https://invis.io/BXEFBA2EF#/262879736_WF_Group_Overview_V2
- [x] nothing is editable in this list
- [x] hide group statistics 

excluded from this first sprint: 
- show group-status like completeness, statistics 
- the tile view and 
- the switch between list and tile view

**Technical details**
- [x] create mockup for page
- [x] remove current tile view
- [x] comment out/remove charts requests
- [x] style the list view (columns image, name, energy sources)
- [x] link to group detail page https://{servername}/localpools/{group-id}
- [x] whole row is linked

**Design and screen Mockup:**

It is the "list"-view to this: https://invis.io/B8EFBOR5C#/258120359_Desktop_HD_-_Desktop_Home
-> same navigation-level. 
List should look similar like this: https://invis.io/C2EFBLRAW#/256909734_Desktop_HD_-_Powertakers 
-> but not editable. 

PW:Wolfgang

**Comment by phillipoertel** [comment]
@evaklopp when you find the time, could you please update the DoD (definition of done) to be clear that the tile/grid view is not relevant, yet? The DoD criteria will likely get shorter by that.

**Comment by evaklopp** [comment]
@phillipoertel done. I excluded it, did you mentit like this?

**Comment by evaklopp** [comment]
Here is the Design for the list, made by Pali: https://invis.io/7MEHKXI5J#/263660407_Desktop_HD_-_Desktop_Home_List_View

**Comment by dottorer** [comment]
Quick questions on the design:
- are these the best columns for the list? What value has the power source icon to Pho?
- should / will there by other cols like address? 
- how does he interact with sorting / filtering with this list?
- do we have default images? One or more like slack?

Looks like a clean list for a start but wanted to check the cols.

**Comment by evaklopp** [comment]
Hooorrrayyy!
