### ISSUE TITLE
information details of a powertaker person

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#51]
**PR**
- https://github.com/buzzn/admin-app/pull/261
- https://github.com/buzzn/core/pull/1358
- https://github.com/buzzn/core/pull/1360

---
**Story**
As PhO/Wolfgang I want to see the information details of a powertaker person.

---
**DoD**

- [x] import the remaining powertaker person data: address, fax, contract number (which links to the contract detail). (Note from Phillip: title, prefix, first name, last name, phone, email are already imported in #25)
- [x] in contracts section: link register label
- [x]  the contract section shows the linked customer-contracts

excluded: 
- edit powertaker data
- PT bank data
- customer number
- contract section: no link to the groupname

---
**XD**

- [x] prepare detail-page for a powertaker, similar to other detail-pages. 
see the screen: https://projects.invisionapp.com/d/main#/console/12205665/267942872/preview

- [x] align on data from the console

- [x] define the needed fields

- [x] adjust Design

---

**Technical details**

_Frontend_

- [x] implement powertaker details page from design
- [x] show default person image
- [x] i18n title and columns 
- [x] link up email address (mailto...)
- [x] show all localpool powertaker contracts of a person (use `?includes=contracts[groups] to load` them

_Backend_

- [x] import not yet imported powertaker fields: address, fax,  contract number
- [x] extend API to return all localpool powertaker contracts of a person (customer)

**Comment by dottorer** [comment]
@evaklopp I think we should import and show the field fax for all persons and organisations. We need to see if we can widen the DoD in this story, should hopefully not be too much effort.

**Comment by dottorer** [comment]
@scsirdx Power taker details look great! One question: I noticed that under contracts, we list the register of the PT contract as a link. When clicking on it, i am taken to the register list, not the specific register. When we use the link from the powertaker list, it gets us there directly.

**Comment by scsirdx** [comment]
@dottorer It's a pre-loader bug. If you try to use any link one more time, it will work. Will fix it in another issue.

**Comment by evaklopp** [comment]
good job, YEAH closing!
