### ISSUE TITLE
As PhO I want to see all the details of the register 2

### ISSUE THREAD

**Issue by eharit** [buzzn/scrum#58]
**PR**
- https://github.com/buzzn/admin-app/pull/249
- https://github.com/buzzn/admin-app/pull/253
- https://github.com/buzzn/core/pull/1303
---
**Story**
As PhO I want to see all the details of a register. 

---
**XD prep**

- [x] Register details page 
  - [x] readings tab: https://projects.invisionapp.com/d/main#/console/12205665/266641260/preview
  - [x] contracts tab:
https://projects.invisionapp.com/d/main#/console/12205665/266638569/preview
  - [x] devices tab: https://projects.invisionapp.com/d/main#/console/12205665/266646622/preview
  - [x] details tab: https://projects.invisionapp.com/d/main#/console/12205665/266646621/preview
- [x] update design according to Eva's wireframe

exluded in #47: 
- edit/update

---

**DoD**
- [x] Display all fields according to design

exclude: 
- 'Power widget' on the top

---

**Technical details**

_Frontend_
- [x] Create the page
  - [x] Add readings tab & pane
  - [x] Add contracts tab & pane
  - [x] Add devices tab & pane
  - [x] Add details tab & pane
- [x] Use seed data to display fields
- [x] Cover parts with under-construction where no data, fake data.

exclude:
- 'Power widget' on the top

**Comment by eharit** [comment]
@scsirdx: @evaklopp has provided German translations in the InVision prototype in the comments.

**Comment by evaklopp** [comment]
@scsirdx I have some questions: 
1. I can see the headline of the edifact.information only like admin.registers.headewrEdifacinformation, is that ok because data is missing? 
2. please translatethe following labels, you can find the translations also in the design: 
Register-Details -> Zählwerk-Details
Seriennummer -> Zählernummer

after that the story i perfect!

**Comment by evaklopp** [comment]
Yipiiyayeah, closing!
