### ISSUE TITLE
As a buzzn user, I want the application pages to load quickly

### ISSUE THREAD

**Issue by phillipoertel** [buzzn/scrum#63]
**PR**

----
**Story**

As a buzzn user, I want the application pages to load quickly so that I can get my work done without having to wait.

----
**DoD**

- [x] Application pages load reliably in under 3 seconds (except group list).
- [x] No additional warm-up time is needed for first opening of pages.

excluded:
- group list performance

----
**Technical details**

Investigate and fix the reason why the application is using more and more memory over time (memory leaking). 

- [x] ~~install rack plugin for inspecting objects/memory~~
- [x] check if the jumps in memory consumption are related to the updates of the postgres DB with a new beekeeper import
- [x] check if/where the Ruby code holds references to objects long gone which then can't be garbage collected.

**Heroku metrics**

![bildschirmfoto 2017-12-01 um 10 08 19](https://user-images.githubusercontent.com/5188/33475713-b6bd16c2-d67f-11e7-9055-19700ed657c9.png)

**Comment by phillipoertel** [comment]
@evaklopp @dottorer our application has memory/response time issues right now, we should investigate that soon.

**Comment by mkristian** [comment]
first we installed newrelics agent on staging which gives more inside into the object allocations, garbage-collector runs, memory consumption, etc.

the rack-plugin I had in mind is: https://github.com/MiniProfiler/rack-mini-profiler but not the right thing for memory leaks.

needs some ObjectSpace statistics, just log them regularly. will come next.

time spent: 2 hours.

**Comment by phillipoertel** [comment]
It looks like rack-mini-profiler can do Memory profiling: https://github.com/MiniProfiler/rack-mini-profiler#memory-profiling, but we could also use the memory_profiler gem (https://github.com/SamSaffron/memory_profiler) standalone. Those reports should allow us to see which code/files are responsible for the sudden increase in memory usage.
If you dive in, I think it would make sense to log the memory stats after every request

**Comment by mkristian** [comment]
the memory profiler is not thread safe: https://github.com/SamSaffron/memory_profiler#usage under note. can not use it in multi-threaded server environment.

OK will install the mini-profiler then and some per request stats.

**Comment by mkristian** [comment]
@dottorer @evaklopp referring to the title of this story:

when you login and receive the list of all groups then we perform a huge amount of database queries: https://gist.github.com/mkristian/3699c7661f1e9bf97e3ba0209da8516d

this is NOT optimised yet but comes with advantage of after this list all the data for 'admin' is already loaded. only checks on update are needed (we might even optimise these checks !)

**Comment by phillipoertel** [comment]
@mkristian regarding the DoD criteria "No additional warm-up time is needed for first opening of pages.": preloading the app after deployment is already in our code: https://github.com/buzzn/core/blob/master/config/puma.rb#L14
I just didn't enable it when migrating to Heroku to keep the sources of errors small. When you have time, could you enable it and test? The file has the whole config Heroku recommends for Puma in it after the __END__ marker, maybe there's more useful stuff to enable (link to docs in file).

**Comment by mkristian** [comment]
so added the puma config and adjusted the DB pool. removed and updated a few more gems.

**Comment by evaklopp** [comment]
@phillipoertel is there sth additionaI I can test despite we talked about this morning? If not, I´ll close it for now.

**Comment by dottorer** [comment]
@evaklopp I am accepting this story as done since it was a time boxed effort for this sprint. We will monitor performance and create specific new stories if issues arise (see #75 for example).  Thanks, Team, for improving our heroku setup this sprint!
