### ISSUE TITLE
As Pho, I want to import correct register technical details

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#64]
PR: 
- https://github.com/buzzn/module-bubbles/pull/28
- https://github.com/buzzn/admin-app/pull/254
- https://github.com/buzzn/core/pull/1314
- https://github.com/buzzn/core/pull/1313

---
**Story:**
As Pho, I want to import correct register technical details.

---
**Definition of done**
Continuation from #2 

- [x] manufacturer name is either "Easymeter" or "Other". If Other, name is stored in new 'Meter Description' field.
- [x] All imported meters have a sequential number within a MPOc for a group. The current numbers should be imported from BK (e.g. 90023/11 ; 90023/12; etc).
- [x] For power generation meters that are two-way meters, the production register (obis 2.8.0) has correctly been labeled and the consumption register is labeled 'CONSUMPTION_COMMON'
- [x] All consumption registers linked to PTc with EEG_Umlage = '-1' are labeled 'CONSUMPTION_COMMON'. No further logic must be applied from BK.
- [x] If no value in BK was found, we use the following defaults:  
  - voltage level is set to "low level"
  - meter size is set to "other"
  - mounting method is set to "three point"
  - manufacturer is set to other if it's not an easy meter
- [x] All register labels have meaningful German and English words
- [x] Each group has exactly one grid_feeding and one grid_consumption register. This can be identified by the register label without further group association. If not there, group setup is incomplete.

---

**Technical details**

_Frontend_

- [x] add German/English translations of register labels (see https://github.com/buzzn/scrum/issues/64#issuecomment-348677989)
- [x] ensure the icons for the power generation sources wind and water are displayed correctly (in overviews).

_Backend_
- [x] add new DB column "manufacturer_description". 
- [x] add new DB column "location_description"
- [x] drop reference to address
- [x] adapt manufacturer name enum (only easy meter and other)
- [x] on import, store manufacturer description in new column when it's not an easy meter.
- [x] adapt import statistics, remove non-easymeters from broker stats
- [x] verify the defaults mentioned in the DoD are set.
- [x] investigate why assigning sequence_number from beekeeper wasn't stored correctly.
- [x] for power generation meters, assign the consumption register "CONSUMPTION_COMMON", the production register "PRODUCTION_XXX"
- [x] add invariant validation to check there's at most one grid feeding and consumption register on the group. 
- [x] complete refactoring of removing grid_feeding_register_id from group (also for grid_consumption_register_id)
  - [x] drop db columns
  - [x] remove associations in Localpool model
  - [x] adapt tests
  - [x] adapt factories/fabricators
- [x] drop unused fields from meters and registers

**Comment by dottorer** [comment]
@evaklopp @phillipoertel story to finalize the nitty gritty for meter / register import. Please review and prioritize for Monday's planning...good enough to estimate?

**Comment by phillipoertel** [comment]
Excellent, it all looks very clear now. If you could could provide the German translations for the labels, there‘d be everything to complete this story.

**Comment by dottorer** [comment]
@phillipoertel I updated the old spec for Labels to include all current wisdom: https://buzzn-team.atlassian.net/wiki/spaces/DEV/pages/2752664/Flow+View+and+Edit+Real+Meters+and+Registers 

List is now:
DEMARCATION_PV = "PV Abgrenzung" / "PV Demarcation"
DEMARCATION_CHP = "BHKW Abgrenzung" / "CHP Demarcation"
DEMARCATION_WATER = "Wasser Abgrenzung" / "Water Demarcation"
DEMARCATION_WIND = "Wind Abgrenzung" / "Wind Demarcation"
PRODUCTION_PV = "PV Produktion" / "PV Production"
PRODUCTION_CHP = "BHKW Produktion" / "CHP Production"
PRODUCTION_WATER = "Wasser Produktion" / "Water Production"
PRODUCTION_WIND = "Wind Produktion" / "Wind Production"
GRID_CONSUMPTION = "ÜGZ Bezug" / "Grid Connection Consumption"
GRID_FEEDING = "ÜGZ Einspeisung" / "Grid Connection Feed-in"
GRID_CONSUMPTION_CORRECTED = "ÜGZ Bezug (korrigiert)" / "Grid Connection Consumption (corrected)"
GRID_FEEDING_CORRECTED = "ÜGZ Einspeisung (korrigiert)" / "Grid Connection Feed-in (corrected)"
OTHER = "Sonstiges" / "Other"
CONSUMPTION = "Bezug" / "Consumption"
CONSUMPTION_COMMON = "Bezug - Allgemeinstrom" / "Consumption - Common"

**Comment by phillipoertel** [comment]
The localpool "Fritz Winter Straße" has a register called "Kleinwindrad" labeled as 'PV Produktion', I'll map that to PRODUCTION_WIND.

**Comment by dottorer** [comment]
@phillipoertel All DoD are checked as done, can I test this ticket for acceptance?

**Comment by phillipoertel** [comment]
The wo PRs which implement the remaining work are still open, Christian is just reviewing them

**Comment by phillipoertel** [comment]
wo —> two

**Comment by dottorer** [comment]
Accepting story after spot testing in console / staging. Possible refinement of import for CONSUMPTION_COMMON register discussed with Philip. Can come later.

Good work on this tics, @phillipoertel !
