### ISSUE TITLE
As a developer, I want to have my production system running on heroku

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#71]
**PR**

---
**Story**
As a developer, I want to have my production system running on heroku to so it is relyable and performant. 

---
**DoD**

- [x] Core (https://core.buzzn.io) is accessible on Heroku and show **last release build**
- [x] console (https://console.buzzn.io) for production data
- [x] uptime monitoring
- [x] NewRelic metrics are availiable
- [x] As PhO I want to login into the production system with username and pw

exclude: 
- performance testing
- performance and reliability for Display App 
- loading is <3 seconds

**Technical details**

- [x] set up Heroku production application and pipeline for core
- [x] set up Heroku production application and pipeline for console
- [x] make the DNS change of core.buzzn.io and console.buzzn.io to Heroku
- [x] choose a more powerful DB 
- [x] set up stunnel for Redis (https://devcenter.heroku.com/articles/securing-heroku-redis)
- [x] install SSL certs for Heroku
- [x] adapt CORS header so it works for display.buzzn.io and admin.buzzn.io
- [x] check if NewRelic or Heroku's monitoring is good enough, or if we need to configure an additional service for uptime monitoring.
- [x] discuss and possibly raise `WEB_CONCURRENCY` to > 1
- [x] change staging to run in RAILS_ENV production
- [x] set up exception notification
- [x] Add an personalized account for PhO and let him know the credentials (Email: `philipp@buzzn.net`). Update: this was implemented with `rake db:seed:pho_user`
- [x] make rake task "deploy:production", which first sets a tag on master and pushes it master (!), then deploys to heroku

**Comment by phillipoertel** [comment]
@mkristian could you install the SSL certificates for core.buzzn.io and console.buzzn.io? The applications and DNS are already set up!
Core: https://dashboard.heroku.com/apps/buzzn-core-production/settings
Console: https://dashboard.heroku.com/apps/buzzn-console-production/settings

**Comment by phillipoertel** [comment]
@mkristian regarding Redis:
- there seems to be no way to connect to it via SSL; I can't find a SSL-enabled plan here: https://elements.heroku.com/addons/heroku-redis 
- Heroku writes: "Redis does not have the ability to encrypt data over the network via SSL or other mechanisms. Connecting to Redis should be done via the dynos from within Heroku." --
 https://devcenter.heroku.com/articles/heroku-redis#external-connections. That sounds as if the connections from Heroku dyno were (more) secure? The Redis instance has an AWS domain, , but maybe they tunnel somehow?

**Comment by phillipoertel** [comment]
@mkristian oh, we need to set up stunnel if we want an SSL tunnel to Redis, now I get it: https://devcenter.heroku.com/articles/securing-heroku-redis

**Comment by phillipoertel** [comment]
@mkristian SSL certs already seem to work for https://core.buzzn.io. But let me know if you think there's anything else to do.

**Comment by mkristian** [comment]
@phillipoertel I am OK with this ssl as it uses the let's encrypt setup. but it does not use our buzzn certificates. @dottorer !?

see also: https://www.ssllabs.com/ssltest/analyze.html?d=core.buzzn.io&s=176.34.239.222&latest

**Comment by mkristian** [comment]
see also the staging-core.buzzn.io: https://www.ssllabs.com/ssltest/analyze.html?d=staging-core.buzzn.io&s=176.34.239.222&latest for comparision

**Comment by dottorer** [comment]
Ideal test would be if we had a version of display and admin running again this new heroku production core. @scsirdx  - what would the steps look like to get the front end apps deployed there? We need to ensure the existing "display.buzzn.io" against AWS core is unaffected for now. Would we temporarily deploy a 'production-display.buzzn.io' running against the heroku core?

**Comment by mkristian** [comment]
we have the develop-admin.buzzn.io wired up to new production server, but only one user is on this system: PhO

**Comment by evaklopp** [comment]
@mkristian @dottorer Did someone provide PhO the link and the credentials for the new production?

**Comment by mkristian** [comment]
@evaklopp I can not say it. their is a task which generates this user with a given password, then I need to deploy the DB and then we/I can tell PhO the credentials. but we need to discuss the password thing, as each time the DB needs to imported again this needs to reused again.

**Comment by evaklopp** [comment]
@dottorer Is there any other way to test it than checking wether the server is alive? If not, I can not test it or have to push it to done unseen

**Comment by evaklopp** [comment]
PhO has credentials now. Awaiting his feedback before closing.

**Comment by dottorer** [comment]
Verified with Pho that he can log into https://develop-admin.buzzn.io/ which frontends our new Production Environment using his credentials. Closing.
