### ISSUE TITLE
As customer I want to see which bubbles are the Allgemeinstrom 

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#72]
**PR**
- https://github.com/buzzn/core/pull/1336
- https://github.com/buzzn/module-bubbles/pull/29
---
**Story**
As customer 
I want to see which bubbles are the Allgemeinstrom
to get to see commonly (by the group used) consumed energy.

---
**XD prep**
- [x] prepare/check the look of bubbles with names, add current kW-value how they behave in the different bubble sizes https://projects.invisionapp.com/d/main#/console/10620153/269962500/comments
- [x] visual distinguish Allgemeinstrom registers from other bubbles, e.g. different color or default Allgemeinstrom-icon, name of the register, value

---

exlude until design is ready:

**DoD**

- [x] show the name of the Allgemeinstrom registers in the bubble
- [x] break line for long register names
- [x] show current power value in unit Watt ("W")
- [x] change color of Allgemeinstrom bubbles to be darker

**Technical Details**

_Frontend_

- [x] render text using d3.js so they fit into bubble
- [x] add ellipsis if text would be longer than two lines
- [x] change color of Allgemeinstrom bubbles to be darker  
- [x] for large power consumptions: display in Watt, add thousands separator (20.000 W)

_Backend_

- [x] add name of the register to the API response of the bubbles

**Comment by eharit** [comment]
Would need some sample register names (Longest one, long ones, and shorter ones) and values with units.

**Comment by dottorer** [comment]
@eharit Register names (For Common Consumption only) can be seen here https://staging-console.buzzn.io/admin/registers?utf8=%E2%9C%93&q%5Blabel_in%5D%5B%5D=CONSUMPTION_COMMON&commit=Filter&order=name_asc

**Comment by evaklopp** [comment]
@eharit I added a comment in inVision: https://projects.invisionapp.com/d/main#/console/10620153/269962500/comments

**Comment by scsirdx** [comment]
- No break line
- Proper unit scaling (W, kW, ...)

**Comment by evaklopp** [comment]
great job, thanks team, closing!

**Comment by evaklopp** [comment]
great job, thanks team, closing!

**Comment by evaklopp** [comment]
great job, thanks team, closing!
