### ISSUE TITLE
Charts of the display app 

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#74]
**PR**
- https://github.com/buzzn/display-app/pull/79
- https://github.com/buzzn/core/pull/1340
- https://github.com/buzzn/core/pull/1342
- https://github.com/buzzn/core/pull/1344
- https://github.com/buzzn/core/pull/1345
- https://github.com/buzzn/core/pull/1346

---

**Story**

As a BUZZN customer I would like to see the charts of the display app, so I can understand how the consumption and production develop over the day. 

---

**DoD**

- [x] Daily line charts underneath the bubbles show correct prod and cons line values.

**Technical Details**

_Frontend_

- [x] verify everything is working
- [x] adjust to new format if needed

_Backend_

- [x] define new types for result
- [x] get readings from Discovergy
- [x] iterate over the readings for consumption and production and put them into the result types
- [x] possibly: line up the timestamps of the results, check if old code can be used for that
- [ ] tests all new services
- [ ] tests for the conditional gets
- [x] cleanup datasource code, i.e. delete obsolete

**Comment by evaklopp** [comment]
@dottorer please lets talk about this story, how we can break it down to smaller parts.

**Comment by dottorer** [comment]
@evaklopp We need to run another estimation round on this one with the team. We need to understand what is still to be done in order for line charts to work efficiently with the new chart API.

**Comment by mkristian** [comment]
just a few thoughts about this:

* group with only discovergy registers is the simplest case
* group with virtual meters is not clear as the virtual meters are not imported and a bit unclear how we are going to deal with them implementation-wise and model-wise
* group with standard-profile meters. we do not import and setup the standard-profile on staging yet, we excluded the import test on CI, standard-profile implementation needs to follow new code.
* virtual-meter with standard profile meter as operand is this possible ?

**Comment by evaklopp** [comment]
@dottorer/ @phillipoertel I woul appreciate if we estimate this after standup tomorrow. Because it is essential and big and we have only one week before xmas. What do you think?

**Comment by mkristian** [comment]
charts are about energy consumed, so I have the feeling the 'current power consumption, total power consumption and production' is not power but energy. otherwise power is more domain of the bubbles from issue #77

**Comment by dottorer** [comment]
@mkristian You are absolutely correct, sloppy DoD from moi. There is a value for total **power** consumption (as in the power consumed by all right now) and there are total **energy** consumption/production (all the energy cons/prod for the current day so far). The autarchy is based on the later in our calcs. 

I updated the DoD, makes more sense now?

**Comment by mkristian** [comment]
better still unclear: `show correct values for current power consumption` from this issue and `all bubbles and energy totals` from #77  - in short bubble are about power and charts about energy.

#77 is about bubbles and this one about energy. just move energy totals here and current power consumption to the bubbles. and probably the energy totals are already here as `total energy consumption and production`. for the autarkie calculation we use the energy data.

**Comment by mkristian** [comment]
@dottorer ---^

**Comment by phillipoertel** [comment]
@mkristian as discussed, the Discovergy password is currently logged on Heroku since the oauth or http library log all requests we do. I made a PR to prevent this, fortunately the latest Faraday version can filter it's log: https://github.com/buzzn/core/pull/1343

**Comment by phillipoertel** [comment]
Btw I'm still not happy that the plain-text credentials are part of the URL, they will be visible for and possibly logged by all intermediaries (like Discovergy's internet provider). 
Are you sure those credentials need to be provided for every request? Shouldn't the oauth token be enough?

**Comment by evaklopp** [comment]
timebox left over work for the rest of today (friday), charts are running.

**Comment by evaklopp** [comment]
closing, missing technical tasks are referenced in the tickets above. DoD is fullfilled. Yeah

**Comment by evaklopp** [comment]
@phillipoertel I didn´t recognized your last comment before closing. I don´t know to whom you asked the question? It was´nt referenced to someone. Kristian? Maybe you have to ask again, or I reopen the story?

**Comment by mkristian** [comment]
@evaklopp there are still two open PR on this ticket. just leave it closed as is, as we are going to merge these PRs today.

**Comment by phillipoertel** [comment]
@evaklopp they were intended for @mkristian. @mkristian are you sure the plain-text password needs to be part of every request to Discovergy?

**Comment by mkristian** [comment]
once we have the token there is no discovergy password sent. the token we get once per process. but this low-level discovergy code is not part of this story or code created/touched.

**Comment by phillipoertel** [comment]
Ok. Not happy about the password being open in Discovergy's server logs, but that's actually the least problem. Github and hub.docker.com also have it, as well as everyone who scrape those sites for passwords in the last months. Additionally it's also in our Heroku logs. 
@dottorer I'll stop bothering you guys here now, but please be aware that this is a significant security issue.

**Comment by mkristian** [comment]
@phillipoertel you are right that we have the discovergy password all over the net. we should look at the oauth once we are going to change the password at discovergy which is hightime to do so.
