### ISSUE TITLE
As PhO, I want the list of groups to load quickly

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#75]
**PR**

---
**Story**
"As PhO, I want the list of groups to load quickly

**DoD**
 follw up of #63 

- [x] load group list <5 seconds

**Technical details**
- [x] use AR's include option to load associated data (Christian knows where)

_Backend_
- [x] add virtual field "power_sources" to JSON for each localpool. It is an array with at least of these values: 'pv', 'chp', 'wind', 'water'.

_Frontend_
- [x] don't request meters and registers any more, use power_sources attribute to display icons.

**Comment by phillipoertel** [comment]
Query stats for loading all localpools:

| Queries | Class |
|---------|-------|
1.005 | Reading::Single
 957 | Register::Real
 115 | Adress
  65 | Meter::Base
  39 | BankAccount
|    2 | Role (already optimized) |

**Comment by evaklopp** [comment]
@phillipoertel can you help me to estimate the stats? Thank you :-)

**Comment by mkristian** [comment]
@phillipoertel 
that is the place where the list is produces:
https://github.com/buzzn/core/blob/master/lib/buzzn/roda/admin/localpool_roda.rb#L129
which would need an extra method one this localpools object like `optimized` or so.

this is the localpools object: https://github.com/buzzn/core/blob/master/lib/buzzn/resource/collection.rb

this is parser for the include parameter: https://github.com/buzzn/core/blob/master/lib/buzzn/include_parser.rb
which produces a nested hash or array usable for the `to_json(include:...)` method. I tried to produce something working with the regular to_json methods on objects and I think the `include` method on AR is using the same notation (not sure though).

currently the parser is used in: https://github.com/buzzn/core/blob/master/lib/buzzn/roda/helpers/serializer.rb#L37

**Comment by mkristian** [comment]
@phillipoertel one more: the extra method on the `Collection` either needs to manipulate the ` @objects` instance which is AR relation or create a cloned `Collection` with the manipulated ` @objects` passed into the constructor.

**Comment by phillipoertel** [comment]
@scsirdx FYI the power_sources array is on master and also deployed to staging, so you can change the requests. We're curious how fast things will be afterwards :-)

**Comment by phillipoertel** [comment]
@evaklopp @dottorer ready to test on staging as well. Great team work by @mkristian @scsirdx and me :-)

**Comment by evaklopp** [comment]
please fasten your seatbelt - very fast loading group list 🎉

**Comment by dottorer** [comment]
Sensational! This now does rock - Well done, tuning team!
