### ISSUE TITLE
Vivid/Fast bubbles in Display View

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#77]
**PR**
* https://github.com/buzzn/core/pull/1326
---
**Story**

As a Buzzn user I want to see my group quickly in Display View.

---
**DoD**

- [x] all bubbles and are initially rendered with good performance in less than 5 seconds 
- [x] the bubbles feel vivid and refresh every 15 seconds. 
- [x] this is possible for all BK-imported groups
- [x] testable via display view

excluded:
- managing a localpool's register changes

**Technical details**

_Backend_

- [x] retrieve virtual meter info from Discovergy
- [x] move code from import to service class, add retrieve method
- [x] create or reuse the existing virtual meters in the beekeeper import
- [x] all BK-imported groups have a virtual group meter definition in Discovergy including all their consumption and production meters

**Comment by mkristian** [comment]
bubbles are about current power consumption but the energy totals can be either taken from the charts or from special energy endpoint which needs to be implemented on the group level. but the charts you will get this info for free

**Comment by phillipoertel** [comment]
@dottorer @evaklopp what about the non-easymeter groups (please consider for next sprint)

**Comment by mkristian** [comment]
@evaklopp both DoD and technical details do not consider the groups which do not have any discovergy meter and can not be boosted in any ways.

**Comment by evaklopp** [comment]
@dottorer As non smart metered groups can´t have live bubbles, those groups can´t have the display view at the moment. Does it makes sense to show anything of the SLPs (Standardlastprofil)?

**Comment by dottorer** [comment]
@evaklopp We can at this point only show groups that have ONLY easymeters providing data values. This is 28 out of 42 groups per Pho. The other 14 have either a mix or no smart meters. They should not get display in the first round.

Talking with @mkristian he came up with the following: For mixed-SM groups (where at least the ÜGZ is smart and the production registers) we could derive the current average consumption per register by dividing the total consumption by the number of registers. Better than SLP for each.

For groups where even the ÜGZ is old school, non-smart, we could use SLP, but to me that negates the need for a display if we only show average German SLP/SEP data. 

We should create stories for "As group owner, I want to see my group in Display View even if not all meters are Easymeters" and take it from there.

**Comment by mkristian** [comment]
I just created the optimised group for the `marktplatz` and here there is two way meter with one consumption-common register and one 'production-chp` register. the optimised group as such seems to be OK as far I can tell, but the bubbles delivered from such a group are not correct.

can not squeeze the fix for this into this story

**Comment by dottorer** [comment]
@mkristian Can you elaborate what is not yet correc twith the bubbles for Marktplatz and what a fix would entail? Hard to see visually what's incorrect in bubbles...

**Comment by mkristian** [comment]
@dottorer it is the handling of the two way meter. so all bubbles need to return positive numbers but on the two way meter registers they return also negative ones and they return the same value for both the production-chp and consumption-common which is also wrong.

example: power for the two-way meter is 
* 12345 mW then we need to return 123W for production-chp and 0 for consumption-common
* -1213 mW then 0W for production-chp and 1 W for consumption-common

**Comment by mkristian** [comment]
@dottorer @evaklopp just click on the `markplatz` on `system` and then on `BHKW Production` - there are two, once you clicked into the register you can not see whether it is the consumption or the production register anymore. a bit confusing to loose this info the moment you click on it. in the overview list the label is still present.

**Comment by mkristian** [comment]
optimizsed groups:
```
am-urtlgraben: 00000109
bahnhofstr: '00000117'
fritz-winter-strasse: '00000111'
gertrud-grunow-strasse: '00000112'
heigelstrasse: '00000106'
karmensoeldnerstrasse: 00000108
landsbergerstrasse: 00000118
marktplatz: '00000122'
martinusstrasse: 00000119
mehrgenerationenplatz-forstenried: '00000120'
reinmarplatz: '00000110'
wagnis: '00000123'
wagnisart-afrika: '00000116'
wagnisart-australien-asien: '00000114'
wagnisart-europa-amerika: '00000115'
woge: '00000113'
```

@dottorer there are more but some meters declared manufacturer-name to be `other` which did not trigger to setup the connection to discovergy. only meters with manufacturer-name `easymeter` gets connected.

we should clean up this and in the same run make the 'datasource' of a meter a field in the DB and drop the complete broker tables as it has no data anymore and is only used to create the 'virtual' field 'datasource' right now. @dottorer you also told me the criteria whether or not it is an easymeter from discovergy is whether the credentials for discovergy are in beekeeper or not.

**Comment by mkristian** [comment]
`Reinmarplatz` still has a problem with bubbles. all others do work. the problem I can fix is the `production pv` meter with one of the registers with label `other`: https://staging-admin.buzzn.io/groups/4c1fb716-107b-40db-a633-8929f03a1bcf/system

**Comment by dottorer** [comment]
@mkristian It is brilliant that we are not actually seeing issues with bubbles that are based on the register labels being off :+1: This level of clarity and control we never had and it will cleanse our data perfectly.

Let me know if there are specific cases for relabeling we need to do in BK prior to the next export...

**Comment by dottorer** [comment]
@mkristian 
[Zaehler_Discovergy_Importdaten.xlsx](https://github.com/buzzn/scrum/files/1582130/Zaehler_Discovergy_Importdaten.xlsx)

In discussion with Pho, we can clearly identify several inconsistencies for meter linkage to Discovergy:
1. Even under the same MPOc (e.g. 90050), there can be some meters with a LCPc ("60025") and other without. Only actual cons or prod meters will need a MPOc number, some demarcation meters can exists without it. We need to ensure that we also import those starting from the minipool_objekte table.
2. In some cases there is a disco user, but it is not a EasyMeter -> analyze
3. Some of the 'berechneterZähler' have connection data which is weird.
4. Some MPOc have LPCs for all meters, but a few missing (e.g. 90002). Might be installed later and never fixed up the data in BK.

Pho to dig into this and analyze for us....

**Comment by evaklopp** [comment]
5 secs, vivid, tested, yeah! Closing before christmas
