### ISSUE TITLE
As resident of Mehrgenerationenplatz I want to see the Display view on the samsung TV

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#81]
**PR**

---
**Story**
As resident of Mehrgenerationenplatz I want to see the Display view on the samsung TV

**DoD**
- [ ] test/check and changes on Tizen TV

**Comment by evaklopp** [comment]
@dottorer have you already checked the TV in the studio/Wogeno?

**Comment by dottorer** [comment]
@evaklopp URL was givne to Justus as he was in Studio last week. Check with him as I have not had access to the TV yet.

**Comment by evaklopp** [comment]
as the TV is not requesting data from our System anymore, I found out via Henri (My contact-person from Wogeno is Katharina, who is in holidays at the moment) that as far as he knows it is switched off.  Furthermore Henri told me, that the next new display is the one at Mehrgenerationsnplatz, so I close this ticket as I assume that we don´t need to adjust more things here.
