### ISSUE TITLE
Powersources of group in the display view

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#83]
**PR**
- https://github.com/buzzn/display-app/pull/76
---
**Story**

As Wolfgang 
I want to see all powersources of my group in the display view 
to show them to my interested tribe. 

**DoD**
- [x] up to three power generators can be displayed in the values on the left tab, in proper colour and icon. 
- [x] the list of power sources in the left tab adapts to the number of power sources (there can be between 1 and 3)".

**Technical details**

_Frontend_

- [x] check that left sidebar still adapts to different numbers of power sources (1-3)
- [x] make sure the application handles 0 power sources correctly

colors: https://projects.invisionapp.com/d/main#/console/10620153/226979321/preview

**Comment by evaklopp** [comment]
new story after splitting #80

**Comment by phillipoertel** [comment]
@evaklopp as suggestion for the DoD: "the list of power sources in the left tab adapts to the number of power sources (there can be between 1 and 3).

**Comment by dottorer** [comment]
@scsirdx For testing purposes, we could use PeoplePowerTestGroup with three power generators and see them all rendered in left col of Display view with proper icons, right? 

![image](https://user-images.githubusercontent.com/14217285/34245444-2b87ecde-e62a-11e7-9bfe-ceea462cff5e.png)

**Comment by evaklopp** [comment]
@scsirdx the pp-testgroup shows only one source in the display view at the moment. But it should show 3, right? Despite this everything is fine for this story.

**Comment by scsirdx** [comment]
@evaklopp No. The group responds with 3 powersources, but bubbles endpoint responds with only 1 production register. So it's a normal behaviour.
Or not? @mkristian

**Comment by dottorer** [comment]
@mkristian To close this out, could we check why the bubbles endpoint responds only with 1 production register? There are 3 defined per Admin App.

Similarly, we can check 'Fritz-Winter-Str' which has 2 PV and one wind generator. Should return those 3 for bubbles.

**Comment by mkristian** [comment]
@dottorer if I go into the those missing registers  from the bubbles then I get a 404 on staging. so there is something deeper broken here.

**Comment by mkristian** [comment]
@dottorer @evaklopp @scsirdx so the missing meter on 'Fritz-Winter-Str'  are registered at discovergy but never delivered any readings to them, i.e. they can not be found on https://my.discovergy.com/dashboard for the same reason: they did not deliver any readings up to now.

still checking the the other group

**Comment by mkristian** [comment]
yes, also the missing registers on pp-testgroup is the same thing: they never got a reading and a such discovergy does not consider them 'online' and do/can not deliver any results.

**Comment by dottorer** [comment]
So we can have a situation where a register is defined as 'EasyMeter' but we never received any values on it from Discovergy. This can be the case if an EasyMeter is installed but not a Meteor interent connection for it. In the cases mentioned above, this is correctly identified and differentiated for those groups.

In my view, we can close this ticket and defer further work for more robust identificatiob of 'live' Easymeters in a different ticket.

**Comment by dottorer** [comment]
@mkristian Last thing to check: The WA10 group has no live wind generator, it was never connected so the BK data is incorrect. However, it has two PV generators:
- Cohaus WA10 - UV-PV K6 |   | Produktion (60300809)
- Cohaus WA10 - PV Dach |   | Produktion (60300807)

Those should both be delivered to the bubbles endpoint separately. Can we verify?






Cohaus WA10 - UV-PV K6 |   | Produktion (60300809)
-- | -- | --

**Comment by mkristian** [comment]
all three production are served via the bubbles endpoint:
```
  {
      "id":"f4730c4f-c3d1-4e59-8bed-20070b711886",
      "label":"production_pv",
      "value":141
   },
--
--
   {
      "id":"3131734d-05d2-4beb-9f6c-d5716736ee6e",
      "label":"production_wind",
      "value":0
   },
--
--
   {
      "id":"15b89424-f10f-4ea6-82a8-b6999b116da1",
      "label":"production_pv",
      "value":33
   },
```

**Comment by dottorer** [comment]
This is perfect, @mkristian . Pho has by now removed the obsolete wind item so the next import corrects that.

Question for @scsirdx : If we have two PV sources, then the icon on the left will show the sumtotal of both and we will have two different arc segments in the middle, right? If so, we can close this ticket.

**Comment by dottorer** [comment]
CLosing as completed - thanks!
