### ISSUE TITLE
Show correct arcs and circle for current power production

### ISSUE THREAD

**Issue by phillipoertel** [buzzn/scrum#85]
**User story**

As a buzzn display user
I want to see the current power production as arcs and cicle
so that my production matches my consumption.

---

**Definition of done**

- [x] for each power source, the arc is show in the matching color and size/length
- [x] display the current production as a green circle

---

**Technical details**

_Frontend_

- [x] add proper colors for water and wind labels
- [x] make sure that each power source is rendered as an arc in the correct size

**Comment by evaklopp** [comment]
yeah, great work, closing!
