### ISSUE TITLE
Show total daily energy consumption and production for group (Tagesverbrauch/produktion)

### ISSUE THREAD

**Issue by phillipoertel** [buzzn/scrum#87]
**PR**
- https://github.com/buzzn/display-app/pull/79
---

**User story**

As a buzzn user
I want to see the total production and consumption of my energy group
so that I know how much we consumed and produced.

---

**Definition of done**

- [x] I can see the total production and consumption of my energy group in kWh
- [x] it updates every 15 minutes

---

**Technical details**

_Frontend_

- [x] verify everything is still working

**Comment by evaklopp** [comment]
yes, it works and updates every 15 minutes. Good job, closing....
