### ISSUE TITLE
Show autarchy based on daily energy consumption vs production

### ISSUE THREAD

**Issue by phillipoertel** [buzzn/scrum#88]
**PR**
- https://github.com/buzzn/display-app/pull/79
---

**User story**

As a buzzn display user
I want to see the daily autarchy
so that I know how self-sufficient my localpool is performing.

---

**Definition of done**
 
- [x] show the autarchy score we currently calculate (in %)

---

**Technical details**

_Frontend_

- [x] check with TT the correct math
- [x] verify the autarchy is still displayed

**Comment by evaklopp** [comment]
good job, closing and trusting your maths ;-)

**Comment by evaklopp** [comment]
good job, closing and trusting your maths ;-)
