### ISSUE TITLE
Show Display view in browsers, tablets

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#89]
**User story**
- https://github.com/buzzn/display-app/pull/78

As a buzzn user
I want see the Display View correctly rendered on my laptop browser and my tablet
so that I can enjoy it anywhere.

---

**Definition of done**

- [x] resizing for different browsers
- [x] it displays correctly on all Chrome, Safari, IE, Firefox, iOS and Android browsers down to the 2nd last version
- [x] when displayed fullscreen (F11), there are no scrollbars, display is centered

excluded: 
- charts
- total daily conumption/production 
- groupowner

---

**Technical details**

_Frontend_

- [x] preserve old styles with a "?display=tizen" query parameter
- [x] implement resizing
- [x] make sure no scrollbars are visible (on fullscreeen, optional all the time)
- [x] test on different browsers

**Comment by scsirdx** [comment]
@dottorer I still can't run properly VM with IE11. While i'm searching for workaround, can you test it in Edge (or maybe even in IE11 if we're supporting it).

**Comment by scsirdx** [comment]
@dottorer I finally was able to run Win10 in parallels. So i can test in Edge, still no IE11 (only IE11 compatibility mode in Edge). So if you have it, please check.

**Comment by evaklopp** [comment]
TEST RESULTS:  
**chrome Version 63.0.3239.84:** ALL GOOD

@scsirdx: 
**Firefox Quantum 57.0.3:** jumps to the right browser-site when screen bigger than 1960x1220 (depends on the hight) and sticks there. Should stay in the center (same gapping left/right). 

**Safari** 
imac: 11.0.2: ALL GOOD
iPhone 6 11.2.1: landscape/portrait: All GOOD
iPad mini 4: 11.2.1: landscape/portrait ALL GOOD 
iPad 2, Version 10.3.3: landscape/portrait ALL GOOD

@dottorer could you please test the IE11 if possible and if you have any other non-apple-tablet/smartphone around you aswell, short feedback would be very helpfull. Thank you.

**Comment by dottorer** [comment]
Testing in IE11, full screen mode, looks good. Minimal difference is that the box around the bubbles has a slight black outline, but no action item.

![image](https://user-images.githubusercontent.com/14217285/34713564-f8c546be-f526-11e7-9158-985353b845ab.png)

**Comment by dottorer** [comment]
Testing in Edge looks great, both full screen mode with title and no-title.

**Comment by scsirdx** [comment]
FF should work fine now. Not perfect in some edge cases (21:9 with huge resolutions), but they're rare.

**Comment by evaklopp** [comment]
Great, thanks, What about the grey lines in IE11? Is this solved aswell or shall we ignore them?

**Comment by dottorer** [comment]
IE is fine as is, we can ignore this edge case

**Comment by evaklopp** [comment]
all good, thanks to all of you, closing

**Comment by evaklopp** [comment]
....hit the wrong button :-) closing now!
