### ISSUE TITLE
Proper information/error for non existing group

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#96]
**PR**
- https://github.com/buzzn/display-app/pull/80
- https://github.com/buzzn/core/pull/1354
---
**User story**

As a BUZZN user 
I want to get a propper notification if I typed in a non existing groupname 
so that I get a clear information.
---
**XD-prep:** 

- [x] provide screen with the following text: 
"Die von Dir gesuchte Seite wurde leider nicht gefunden.
Erfahre mehr über www.buzzn.net"  

translation: "unfortunately the site you are looking for does not exist on our servers"

InVision Mock Up: https://projects.invisionapp.com/d/main#/console/10620153/270244031/preview

**Definition of done**

- [x] show above provided screen if someone enters a URL for a non-existing group such as "display.buzzn.io/nogroup"

---

**Technical details**

_Frontend_

- [x] when API returns a 404, render the above German text.

**Comment by evaklopp** [comment]
@eharit @dottorer we could add a link to BUZZN-contact on the website or even ask the user, if he wants to start a group a new group (because the one he/she is looking for does not yet exist)

**Comment by eharit** [comment]
added invision mockup: https://projects.invisionapp.com/d/main#/console/10620153/270244031/preview

**Comment by evaklopp** [comment]
@eharit two changes, documented in InVision.

**Comment by eharit** [comment]
Screen updated, see result in InVision

**Comment by evaklopp** [comment]
thanks for updating!

**Comment by evaklopp** [comment]
@scsirdx see inVision link for new 404 screen, if any page is not availiable anymore.

**Comment by evaklopp** [comment]
@scsirdx is this ticket already done?

**Comment by evaklopp** [comment]
@scsirdx if I type in any non existing group name like /lalelu, I still get the "your group is currently not availiable"-screen, not the 404 - page which is provided via the Invision screen linked in the story. Can you please check?

**Comment by evaklopp** [comment]
@scsirdx ok now I checked https://staging-display.buzzn.io/lalelu and it looks like this: 
![bildschirmfoto 2018-01-16 um 09 30 14](https://user-images.githubusercontent.com/22292464/34978863-efdc28b4-fa9f-11e7-8599-227a955f34e9.png)

but should look more ore less like this (like inVision-screen above): 
![bildschirmfoto 2018-01-16 um 09 31 19](https://user-images.githubusercontent.com/22292464/34978892-0c97ed4e-faa0-11e7-96e6-aba06930708a.png)

**Comment by scsirdx** [comment]
@mkristian I found a bug:
- `https://staging-display.buzzn.io/people-power-group-testgruppefdsfsd` invalid url with 404
- `https://staging-display.buzzn.io/people-power-group-testgruppe543534534` valid url, and all needed data is loaded.

**Comment by mkristian** [comment]
@scsirdx the code makes a slug out of `people-power-group-testgruppe543534534` which is `people-power-group-testgruppe`. can make it more strict.

**Comment by evaklopp** [comment]
looks perfect, story tested and approved, can go to production. closing.
